/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './home.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from '../shared/shared.module';
import * as import7 from './home-routing.module';
import * as import8 from '../+post/post.module';
import * as import9 from '../+postDetail/postDetail.module';
import * as import10 from '@angular/core/src/application_module';
import * as import11 from '@angular/platform-browser/src/browser';
import * as import12 from '@angular/common/src/localization';
import * as import13 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import14 from '@angular/forms/src/form_builder';
import * as import15 from '@angular/core/src/application_init';
import * as import16 from '@angular/core/src/testability/testability';
import * as import17 from '@angular/core/src/application_ref';
import * as import18 from '@angular/core/src/linker/compiler';
import * as import19 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import20 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import21 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import22 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import23 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import24 from '@angular/core/src/linker/view_utils';
import * as import25 from '@angular/platform-browser/src/browser/title';
import * as import26 from '@angular/core/src/di/injector';
import * as import27 from './home.component.ngfactory';
import * as import28 from './home.component';
import * as import29 from '@angular/core/src/application_tokens';
import * as import30 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import31 from '@angular/platform-browser/src/dom/events/key_events';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import34 from '@angular/core/src/console';
import * as import35 from '@angular/core/src/i18n/tokens';
import * as import36 from '@angular/router/src/router_config_loader';
import * as import37 from '@angular/core/src/error_handler';
import * as import38 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import39 from '@angular/platform-browser/src/dom/animation_driver';
import * as import40 from '@angular/core/src/render/api';
import * as import41 from '@angular/core/src/security';
import * as import42 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import43 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class HomeModuleInjector extends import0.NgModuleInjector<import1.HomeModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _ReactiveFormsModule_4:import5.ReactiveFormsModule;
  _SharedModule_5:import6.SharedModule;
  _HomeRoutingModule_6:import7.HomeRoutingModule;
  _PostModule_7:import8.PostModule;
  _PostDetailModule_8:import9.PostDetailModule;
  _ApplicationModule_9:import10.ApplicationModule;
  _BrowserModule_10:import11.BrowserModule;
  _HomeModule_11:import1.HomeModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import12.NgLocaleLocalization;
  __RadioControlRegistry_14:import13.RadioControlRegistry;
  __FormBuilder_15:import14.FormBuilder;
  __ROUTES_16:any[];
  _ErrorHandler_17:any;
  _ApplicationInitStatus_18:import15.ApplicationInitStatus;
  _Testability_19:import16.Testability;
  _ApplicationRef__20:import17.ApplicationRef_;
  __ApplicationRef_21:any;
  __Compiler_22:import18.Compiler;
  __APP_ID_23:any;
  __DOCUMENT_24:any;
  __HAMMER_GESTURE_CONFIG_25:import19.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_26:any[];
  __EventManager_27:import20.EventManager;
  __DomSharedStylesHost_28:import21.DomSharedStylesHost;
  __AnimationDriver_29:any;
  __DomRootRenderer_30:import22.DomRootRenderer_;
  __RootRenderer_31:any;
  __DomSanitizer_32:import23.DomSanitizerImpl;
  __Sanitizer_33:any;
  __ViewUtils_34:import24.ViewUtils;
  __IterableDiffers_35:any;
  __KeyValueDiffers_36:any;
  __SharedStylesHost_37:any;
  __Title_38:import25.Title;
  constructor(parent:import26.Injector) {
    super(parent,[
      import27.HomeComponentNgFactory,
      import27.HomeComponentNgFactory,
      import27.HomeComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == (null as any))) { (this.__LOCALE_ID_12 = 'en-US'); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import12.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == (null as any))) { (this.__NgLocalization_13 = new import12.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _RadioControlRegistry_14():import13.RadioControlRegistry {
    if ((this.__RadioControlRegistry_14 == (null as any))) { (this.__RadioControlRegistry_14 = new import13.RadioControlRegistry()); }
    return this.__RadioControlRegistry_14;
  }
  get _FormBuilder_15():import14.FormBuilder {
    if ((this.__FormBuilder_15 == (null as any))) { (this.__FormBuilder_15 = new import14.FormBuilder()); }
    return this.__FormBuilder_15;
  }
  get _ROUTES_16():any[] {
      if ((this.__ROUTES_16 == (null as any))) { (this.__ROUTES_16 = [[
        {
          path: 'blog',
          component: import28.HomeComponent
        }
        ,
        {
          path: 'blog/:idCategory/:category',
          component: import28.HomeComponent
        }
        ,
        {
          path: 'blog/:idCategory/:idPost/:post',
          component: import28.HomeComponent
        }

      ]
    ]); }
    return this.__ROUTES_16;
  }
  get _ApplicationRef_21():any {
    if ((this.__ApplicationRef_21 == (null as any))) { (this.__ApplicationRef_21 = this._ApplicationRef__20); }
    return this.__ApplicationRef_21;
  }
  get _Compiler_22():import18.Compiler {
    if ((this.__Compiler_22 == (null as any))) { (this.__Compiler_22 = new import18.Compiler()); }
    return this.__Compiler_22;
  }
  get _APP_ID_23():any {
    if ((this.__APP_ID_23 == (null as any))) { (this.__APP_ID_23 = import29._appIdRandomProviderFactory()); }
    return this.__APP_ID_23;
  }
  get _DOCUMENT_24():any {
    if ((this.__DOCUMENT_24 == (null as any))) { (this.__DOCUMENT_24 = import11._document()); }
    return this.__DOCUMENT_24;
  }
  get _HAMMER_GESTURE_CONFIG_25():import19.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_25 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_25 = new import19.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_25;
  }
  get _EVENT_MANAGER_PLUGINS_26():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_26 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_26 = [
      new import30.DomEventsPlugin(),
      new import31.KeyEventsPlugin(),
      new import19.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_25)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_26;
  }
  get _EventManager_27():import20.EventManager {
    if ((this.__EventManager_27 == (null as any))) { (this.__EventManager_27 = new import20.EventManager(this._EVENT_MANAGER_PLUGINS_26,this.parent.get(import32.NgZone))); }
    return this.__EventManager_27;
  }
  get _DomSharedStylesHost_28():import21.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_28 == (null as any))) { (this.__DomSharedStylesHost_28 = new import21.DomSharedStylesHost(this._DOCUMENT_24)); }
    return this.__DomSharedStylesHost_28;
  }
  get _AnimationDriver_29():any {
    if ((this.__AnimationDriver_29 == (null as any))) { (this.__AnimationDriver_29 = import11._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_29;
  }
  get _DomRootRenderer_30():import22.DomRootRenderer_ {
    if ((this.__DomRootRenderer_30 == (null as any))) { (this.__DomRootRenderer_30 = new import22.DomRootRenderer_(this._DOCUMENT_24,this._EventManager_27,this._DomSharedStylesHost_28,this._AnimationDriver_29)); }
    return this.__DomRootRenderer_30;
  }
  get _RootRenderer_31():any {
    if ((this.__RootRenderer_31 == (null as any))) { (this.__RootRenderer_31 = import33._createConditionalRootRenderer(this._DomRootRenderer_30,this.parent.get(import33.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_31;
  }
  get _DomSanitizer_32():import23.DomSanitizerImpl {
    if ((this.__DomSanitizer_32 == (null as any))) { (this.__DomSanitizer_32 = new import23.DomSanitizerImpl()); }
    return this.__DomSanitizer_32;
  }
  get _Sanitizer_33():any {
    if ((this.__Sanitizer_33 == (null as any))) { (this.__Sanitizer_33 = this._DomSanitizer_32); }
    return this.__Sanitizer_33;
  }
  get _ViewUtils_34():import24.ViewUtils {
    if ((this.__ViewUtils_34 == (null as any))) { (this.__ViewUtils_34 = new import24.ViewUtils(this._RootRenderer_31,this._APP_ID_23,this._Sanitizer_33)); }
    return this.__ViewUtils_34;
  }
  get _IterableDiffers_35():any {
    if ((this.__IterableDiffers_35 == (null as any))) { (this.__IterableDiffers_35 = import10._iterableDiffersFactory()); }
    return this.__IterableDiffers_35;
  }
  get _KeyValueDiffers_36():any {
    if ((this.__KeyValueDiffers_36 == (null as any))) { (this.__KeyValueDiffers_36 = import10._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_36;
  }
  get _SharedStylesHost_37():any {
    if ((this.__SharedStylesHost_37 == (null as any))) { (this.__SharedStylesHost_37 = this._DomSharedStylesHost_28); }
    return this.__SharedStylesHost_37;
  }
  get _Title_38():import25.Title {
    if ((this.__Title_38 == (null as any))) { (this.__Title_38 = new import25.Title()); }
    return this.__Title_38;
  }
  createInternal():import1.HomeModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._ReactiveFormsModule_4 = new import5.ReactiveFormsModule();
    this._SharedModule_5 = new import6.SharedModule();
    this._HomeRoutingModule_6 = new import7.HomeRoutingModule();
    this._PostModule_7 = new import8.PostModule();
    this._PostDetailModule_8 = new import9.PostDetailModule();
    this._ApplicationModule_9 = new import10.ApplicationModule();
    this._BrowserModule_10 = new import11.BrowserModule(this.parent.get(import11.BrowserModule,(null as any)));
    this._HomeModule_11 = new import1.HomeModule();
    this._ErrorHandler_17 = import11.errorHandler();
    this._ApplicationInitStatus_18 = new import15.ApplicationInitStatus(this.parent.get(import15.APP_INITIALIZER,(null as any)));
    this._Testability_19 = new import16.Testability(this.parent.get(import32.NgZone));
    this._ApplicationRef__20 = new import17.ApplicationRef_(this.parent.get(import32.NgZone),this.parent.get(import34.Console),this,this._ErrorHandler_17,this,this._ApplicationInitStatus_18,this.parent.get(import16.TestabilityRegistry,(null as any)),this._Testability_19);
    return this._HomeModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.SharedModule)) { return this._SharedModule_5; }
    if ((token === import7.HomeRoutingModule)) { return this._HomeRoutingModule_6; }
    if ((token === import8.PostModule)) { return this._PostModule_7; }
    if ((token === import9.PostDetailModule)) { return this._PostDetailModule_8; }
    if ((token === import10.ApplicationModule)) { return this._ApplicationModule_9; }
    if ((token === import11.BrowserModule)) { return this._BrowserModule_10; }
    if ((token === import1.HomeModule)) { return this._HomeModule_11; }
    if ((token === import35.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import12.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import13.RadioControlRegistry)) { return this._RadioControlRegistry_14; }
    if ((token === import14.FormBuilder)) { return this._FormBuilder_15; }
    if ((token === import36.ROUTES)) { return this._ROUTES_16; }
    if ((token === import37.ErrorHandler)) { return this._ErrorHandler_17; }
    if ((token === import15.ApplicationInitStatus)) { return this._ApplicationInitStatus_18; }
    if ((token === import16.Testability)) { return this._Testability_19; }
    if ((token === import17.ApplicationRef_)) { return this._ApplicationRef__20; }
    if ((token === import17.ApplicationRef)) { return this._ApplicationRef_21; }
    if ((token === import18.Compiler)) { return this._Compiler_22; }
    if ((token === import29.APP_ID)) { return this._APP_ID_23; }
    if ((token === import38.DOCUMENT)) { return this._DOCUMENT_24; }
    if ((token === import19.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_25; }
    if ((token === import20.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_26; }
    if ((token === import20.EventManager)) { return this._EventManager_27; }
    if ((token === import21.DomSharedStylesHost)) { return this._DomSharedStylesHost_28; }
    if ((token === import39.AnimationDriver)) { return this._AnimationDriver_29; }
    if ((token === import22.DomRootRenderer)) { return this._DomRootRenderer_30; }
    if ((token === import40.RootRenderer)) { return this._RootRenderer_31; }
    if ((token === import23.DomSanitizer)) { return this._DomSanitizer_32; }
    if ((token === import41.Sanitizer)) { return this._Sanitizer_33; }
    if ((token === import24.ViewUtils)) { return this._ViewUtils_34; }
    if ((token === import42.IterableDiffers)) { return this._IterableDiffers_35; }
    if ((token === import43.KeyValueDiffers)) { return this._KeyValueDiffers_36; }
    if ((token === import21.SharedStylesHost)) { return this._SharedStylesHost_37; }
    if ((token === import25.Title)) { return this._Title_38; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__20.ngOnDestroy();
  }
}
export const HomeModuleNgFactory:import0.NgModuleFactory<import1.HomeModule> = new import0.NgModuleFactory(HomeModuleInjector,import1.HomeModule);