/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './about.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../shared/model/model.service';
import * as import9 from '@angular/platform-browser/src/browser/title';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './about.component.css.shim';
import * as import13 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/core/src/security';
export class Wrapper_AboutComponent {
  context:import0.AboutComponent;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.AboutComponent(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AboutComponent_Host:import2.RenderComponentType = (null as any);
class _View_AboutComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AboutComponent_0_4:Wrapper_AboutComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AboutComponent_Host0,renderType_AboutComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'about',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AboutComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AboutComponent_0_4 = new Wrapper_AboutComponent(this.parentInjector.get(import8.ModelService),this.parentInjector.get(import9.Title));
    this._appEl_0.initComponent(this._AboutComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AboutComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AboutComponent) && (0 === requestNodeIndex))) { return this._AboutComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AboutComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AboutComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AboutComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AboutComponent_Host === (null as any))) { (renderType_AboutComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AboutComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AboutComponentNgFactory:import11.ComponentFactory<import0.AboutComponent> = new import11.ComponentFactory<import0.AboutComponent>('about',viewFactory_AboutComponent_Host0,import0.AboutComponent);
const styles_AboutComponent:any[] = [import12.styles];
var renderType_AboutComponent:import2.RenderComponentType = (null as any);
class _View_AboutComponent0 extends import1.AppView<import0.AboutComponent> {
  _anchor_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import13.Wrapper_NgIf;
  _pipe_safeHtml_0:import0.SafeHtmlPipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AboutComponent0,renderType_AboutComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import14.TemplateRef_(this._appEl_0,viewFactory_AboutComponent1);
    this._NgIf_0_6 = new import13.Wrapper_NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this._pipe_safeHtml_0 = new import0.SafeHtmlPipe(this.parentInjector.get(import15.DomSanitizer));
    this.init(([] as any[]),[this._anchor_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import16.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = ((this.context.page == (null as any))? (null as any): this.context.page.better_featured_image.source_url);
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.detectChangesInInputProps(this,this._anchor_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_AboutComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AboutComponent> {
  if ((renderType_AboutComponent === (null as any))) { (renderType_AboutComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_AboutComponent,{})); }
  return new _View_AboutComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AboutComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  _pipe_safeHtml_0_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AboutComponent1,renderType_AboutComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'class','aboutContainer'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','aboutContent'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','aboutThumb'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'img',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','content'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_9,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_safeHtml_0_0 = import4.pureProxy1((<_View_AboutComponent0>this.parent)._pipe_safeHtml_0.transform.bind((<_View_AboutComponent0>this.parent)._pipe_safeHtml_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_18:any = this.parent.context.page.better_featured_image.source_url;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_18));
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this.parent.context.page.title.rendered;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementProperty(this._el_6,'alt',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import4.interpolate(1,'',this.parent.context.page.title.rendered,'');
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_12,currVal_20);
      this._expr_20 = currVal_20;
    }
    valUnwrapper.reset();
    const currVal_21:any = valUnwrapper.unwrap(import4.castByValue(this._pipe_safeHtml_0_0,(<_View_AboutComponent0>this.parent)._pipe_safeHtml_0.transform)(this.parent.context.page.content.rendered));
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_21,currVal_21))) {
      this.renderer.setElementProperty(this._el_14,'innerHTML',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.HTML,currVal_21));
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AboutComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AboutComponent1(viewUtils,parentInjector,declarationEl);
}