/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './post.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '../shared/model/model.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './post.component.css.shim';
import * as import13 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import17 from '@angular/router/src/router_state';
import * as import18 from '@angular/common/src/location/location_strategy';
import * as import19 from '@angular/router/src/directives/router_link';
import * as import20 from '@angular/core/src/security';
export class Wrapper_PostComponent {
  context:import0.PostComponent;
  changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.PostComponent(p0,p1);
    this._expr_0 = import1.UNINITIALIZED;
  }
  check_post(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this.changed = true;
      this.context.post = currValue;
      this._expr_0 = currValue;
    }
  }
  detectChangesInInputProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_PostComponent_Host:import4.RenderComponentType = (null as any);
class _View_PostComponent_Host0 extends import3.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _PostComponent_0_4:Wrapper_PostComponent;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_PostComponent_Host0,renderType_PostComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = import2.selectOrCreateRenderHostElement(this.renderer,'post',import2.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PostComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PostComponent_0_4 = new Wrapper_PostComponent(this.parentInjector.get(import8.ModelService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._PostComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PostComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PostComponent) && (0 === requestNodeIndex))) { return this._PostComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PostComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._PostComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PostComponent_Host0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  if ((renderType_PostComponent_Host === (null as any))) { (renderType_PostComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PostComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const PostComponentNgFactory:import11.ComponentFactory<import0.PostComponent> = new import11.ComponentFactory<import0.PostComponent>('post',viewFactory_PostComponent_Host0,import0.PostComponent);
const styles_PostComponent:any[] = [import12.styles];
var renderType_PostComponent:import4.RenderComponentType = (null as any);
class _View_PostComponent0 extends import3.AppView<import0.PostComponent> {
  _anchor_0:any;
  /*private*/ _appEl_0:import5.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import13.Wrapper_NgIf;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_PostComponent0,renderType_PostComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import5.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import14.TemplateRef_(this._appEl_0,viewFactory_PostComponent1);
    this._NgIf_0_6 = new import13.Wrapper_NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this.init(([] as any[]),[this._anchor_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import15.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = ((this.context.post == (null as any))? (null as any): this.context.post.better_featured_image.media_details.sizes.medium.source_url);
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.detectChangesInInputProps(this,this._anchor_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_PostComponent0(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<import0.PostComponent> {
  if ((renderType_PostComponent === (null as any))) { (renderType_PostComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_PostComponent,{})); }
  return new _View_PostComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_PostComponent1 extends import3.AppView<any> {
  _text_0:any;
  _el_1:any;
  _RouterLinkWithHref_1_3:import16.Wrapper_RouterLinkWithHref;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _arr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement) {
    super(_View_PostComponent1,renderType_PostComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways);
    this._arr_13 = import2.pureProxy4((p0:any,p1:any,p2:any,p3:any):any[] => {
      return [
        p0,
        p1,
        p2,
        p3
      ]
      ;
    });
    this._expr_14 = import1.UNINITIALIZED;
    this._expr_15 = import1.UNINITIALIZED;
    this._expr_16 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_1 = import2.createRenderElement(this.renderer,(null as any),'a',new import2.InlineArray2(2,'class','card'),(null as any));
    this._RouterLinkWithHref_1_3 = new import16.Wrapper_RouterLinkWithHref(this.parentInjector.get(import9.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import2.createRenderElement(this.renderer,this._el_1,'figure',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_5 = import2.createRenderElement(this.renderer,this._el_3,'img',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_7 = import2.createRenderElement(this.renderer,this._el_3,'figcaption',import2.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this.init(([] as any[]).concat([
      this._text_0,
      this._el_1,
      this._text_11
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RouterLinkWithHref) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_1_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this._arr_13('/blog',((this.parent.context.post == (null as any))? (null as any): this.parent.context.post.categories)[0],this.parent.context.post.id,this.parent.context.post.slug);
    this._RouterLinkWithHref_1_3.check_routerLink(currVal_1_0_0,throwOnChange,false);
    this._RouterLinkWithHref_1_3.detectChangesInInputProps(this,this._el_1,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_1_3.detectChangesInHostProps(this,this._el_1,throwOnChange);
    const currVal_14:any = this.parent.context.post.better_featured_image.media_details.sizes.medium.source_url;
    if (import2.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_5,'src',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.parent.context.post.title.rendered;
    if (import2.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementProperty(this._el_5,'alt',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import2.interpolate(1,'\n        ',this.parent.context.post.title.rendered,'\n      ');
    if (import2.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_8,currVal_16);
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_1_3.context.ngOnDestroy();
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_1_0:any = ((<any>this._RouterLinkWithHref_1_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_1_0);
  }
}
function viewFactory_PostComponent1(viewUtils:import2.ViewUtils,parentInjector:import6.Injector,declarationEl:import5.AppElement):import3.AppView<any> {
  return new _View_PostComponent1(viewUtils,parentInjector,declarationEl);
}