/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './search.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../shared/model/model.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './search.component.css.shim';
import * as import12 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import17 from '@angular/common/src/pipes/date_pipe';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/i18n/tokens';
import * as import22 from '@angular/forms/src/directives/default_value_accessor';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/common/src/directives/ng_if';
import * as import28 from '@angular/common/src/directives/ng_for';
import * as import29 from '@angular/core/src/security';
import * as import30 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import31 from '@angular/router/src/router';
import * as import32 from '@angular/router/src/router_state';
import * as import33 from '@angular/common/src/location/location_strategy';
import * as import34 from '@angular/router/src/directives/router_link';
export class Wrapper_SearchComponent {
  context:import0.SearchComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.SearchComponent(p0);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_SearchComponent_Host:import2.RenderComponentType = (null as any);
class _View_SearchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SearchComponent_0_4:Wrapper_SearchComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchComponent_Host0,renderType_SearchComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'search',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchComponent_0_4 = new Wrapper_SearchComponent(this.parentInjector.get(import8.ModelService));
    this._appEl_0.initComponent(this._SearchComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SearchComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SearchComponent) && (0 === requestNodeIndex))) { return this._SearchComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SearchComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._SearchComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SearchComponent_Host === (null as any))) { (renderType_SearchComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SearchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchComponentNgFactory:import10.ComponentFactory<import0.SearchComponent> = new import10.ComponentFactory<import0.SearchComponent>('search',viewFactory_SearchComponent_Host0,import0.SearchComponent);
const styles_SearchComponent:any[] = [import11.styles];
var renderType_SearchComponent:import2.RenderComponentType = (null as any);
class _View_SearchComponent0 extends import1.AppView<import0.SearchComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _DefaultValueAccessor_2_3:import12.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_2_4:any[];
  _NgModel_2_5:import13.Wrapper_NgModel;
  _NgControl_2_6:any;
  _NgControlStatus_2_7:import14.Wrapper_NgControlStatus;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import15.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import16.Wrapper_NgFor;
  _text_9:any;
  _text_10:any;
  _pipe_date_0:import17.DatePipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchComponent0,renderType_SearchComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','search-container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'input',new import4.InlineArray8(6,'class','searchInput','placeholder','Search + Enter','type','text'),(null as any));
    this._DefaultValueAccessor_2_3 = new import12.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_2));
    this._NG_VALUE_ACCESSOR_2_4 = [this._DefaultValueAccessor_2_3.context];
    this._NgModel_2_5 = new import13.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_2_4);
    this._NgControl_2_6 = this._NgModel_2_5.context;
    this._NgControlStatus_2_7 = new import14.Wrapper_NgControlStatus(this._NgControl_2_6);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_4 = new import3.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import19.TemplateRef_(this._appEl_4,viewFactory_SearchComponent1);
    this._NgIf_4_6 = new import15.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','search-content'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_8 = new import3.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import19.TemplateRef_(this._appEl_8,viewFactory_SearchComponent2);
    this._NgFor_8_6 = new import16.Wrapper_NgFor(this._appEl_8.vcRef,this._TemplateRef_8_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_9 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngModelChange',this.eventHandler(this._handle_ngModelChange_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'keyup.enter',this.eventHandler(this._handle_keyup_enter_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'input',this.eventHandler(this._handle_input_2_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_2,'blur',this.eventHandler(this._handle_blur_2_3.bind(this)));
    const subscription_0:any = this._NgModel_2_5.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_2_0.bind(this)));
    this._pipe_date_0 = new import17.DatePipe(this.parentInjector.get(import21.LOCALE_ID));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.DefaultValueAccessor) && (2 === requestNodeIndex))) { return this._DefaultValueAccessor_2_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (2 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_2_4; }
    if (((token === import24.NgModel) && (2 === requestNodeIndex))) { return this._NgModel_2_5.context; }
    if (((token === import25.NgControl) && (2 === requestNodeIndex))) { return this._NgControl_2_6; }
    if (((token === import26.NgControlStatus) && (2 === requestNodeIndex))) { return this._NgControlStatus_2_7.context; }
    if (((token === import19.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import27.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import19.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import28.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_2_3.detectChangesInInputProps(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = this.context.keyword;
    this._NgModel_2_5.check_model(currVal_2_1_0,throwOnChange,false);
    this._NgModel_2_5.detectChangesInInputProps(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_7.detectChangesInInputProps(this,this._el_2,throwOnChange);
    const currVal_4_0_0:boolean = !this.context.listStatus;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.detectChangesInInputProps(this,this._anchor_4,throwOnChange);
    const currVal_8_0_0:any = this.context.listItems;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.detectChangesInInputProps(this,this._anchor_8,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._DefaultValueAccessor_2_3.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this._NgModel_2_5.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_7.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_2_5.context.ngOnDestroy();
  }
  private _handle_ngModelChange_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>(this.context.keyword = $event)) !== false);
    return (true && pd_2_0);
  }
  private _handle_keyup_enter_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this.context.getItems()) !== false);
    return (true && pd_2_0);
  }
  private _handle_input_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this._DefaultValueAccessor_2_3.context.onChange($event.target.value)) !== false);
    return (true && pd_2_0);
  }
  private _handle_blur_2_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this._DefaultValueAccessor_2_3.context.onTouched()) !== false);
    return (true && pd_2_0);
  }
}
export function viewFactory_SearchComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SearchComponent> {
  if ((renderType_SearchComponent === (null as any))) { (renderType_SearchComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_SearchComponent,{})); }
  return new _View_SearchComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent1 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchComponent1,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_6 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._text_0 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'class','noItem'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'img',new import4.InlineArray2(2,'alt','Không có bài viết nào trong mục này'),(null as any));
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.init(([] as any[]).concat([
      this._text_0,
      this._el_1,
      this._text_5
    ]
    ),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_6:any = this.parent.context.lolipop;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_3,'src',this.viewUtils.sanitizer.sanitize(import29.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SearchComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_SearchComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import30.Wrapper_RouterLinkWithHref;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _arr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  _pipe_date_0_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchComponent2,renderType_SearchComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_10 = import4.pureProxy4((p0:any,p1:any,p2:any,p3:any):any[] => {
      return [
        p0,
        p1,
        p2,
        p3
      ]
      ;
    });
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'class','card'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_2_3 = new import30.Wrapper_RouterLinkWithHref(this.parent.parentInjector.get(import31.Router),this.parent.parentInjector.get(import32.ActivatedRoute),this.parent.parentInjector.get(import33.LocationStrategy));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_2,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_0,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._pipe_date_0_0 = import4.pureProxy2((<_View_SearchComponent0>this.parent)._pipe_date_0.transform.bind((<_View_SearchComponent0>this.parent)._pipe_date_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkWithHref_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_2_0_0:any = this._arr_10('/blog',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.categories)[0],this.context.$implicit.id,this.context.$implicit.slug);
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_0,throwOnChange,false);
    this._RouterLinkWithHref_2_3.detectChangesInInputProps(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_2_3.detectChangesInHostProps(this,this._el_2,throwOnChange);
    const currVal_11:any = import4.interpolate(1,'',this.context.$implicit.title.rendered,'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_4,currVal_11);
      this._expr_11 = currVal_11;
    }
    valUnwrapper.reset();
    const currVal_12:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,(<_View_SearchComponent0>this.parent)._pipe_date_0.transform)(this.context.$implicit.date,'dd/MM/yyyy')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_12,currVal_12))) {
      this.renderer.setText(this._text_7,currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.context.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this._RouterLinkWithHref_2_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_2_0);
  }
}
function viewFactory_SearchComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SearchComponent2(viewUtils,parentInjector,declarationEl);
}