/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.search-container[_ngcontent-%COMP%] {\n    max-width: 800px;\n    width: 100%;\n    margin: auto;\n}\n.searchInput[_ngcontent-%COMP%] {\n    height: 50px;\n    width: 100%;\n    border: none;\n    outline-width: 0;\n    border-bottom: solid 3px #4db6ac;\n    background-color: #FAFAFA;\n    font-size: 30px;\n    margin-top: 50px\n}\n.noItem[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\n    display: block;\n    width: 200px;\n    margin: 60px auto;\n}\n.search-content[_ngcontent-%COMP%] {\n    margin-top: 50px;\n}\n.search-content[_ngcontent-%COMP%]   .card[_ngcontent-%COMP%] {\n    margin-bottom: 20px;\n    border-radius: 4px;\n    padding: 20px;\n    -webkit-box-shadow: 0px 4px 9px 0px rgba(0,0,0,0.19);\n    -moz-box-shadow: 0px 4px 9px 0px rgba(0,0,0,0.19);\n    box-shadow: 0px 4px 9px 0px rgba(0,0,0,0.19);\n}\n.search-content[_ngcontent-%COMP%]   .card[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\n    font-size: 1.5rem\n}\n.search-content[_ngcontent-%COMP%]   .card[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\n    font-size: 0.8rem\n}'];