/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './shared/model/model.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import16 from '@angular/router/src/router';
import * as import17 from '@angular/router/src/router_state';
import * as import18 from '@angular/common/src/location/location_strategy';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import22 from '@angular/router/src/router_outlet_map';
import * as import23 from '@angular/core/src/linker/component_factory_resolver';
import * as import24 from '@angular/router/src/directives/router_link';
import * as import25 from '@angular/router/src/directives/router_link_active';
import * as import26 from '@angular/common/src/directives/ng_for';
import * as import27 from '@angular/router/src/directives/router_outlet';
import * as import28 from '@angular/core/src/security';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.AppComponent(p0);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
export class Wrapper_XLargeDirective {
  context:import0.XLargeDirective;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.XLargeDirective(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent(this.parentInjector.get(import8.ModelService));
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    var disposable_0:Function = this.renderer.listenGlobal('window','scroll',this.eventHandler(this._handle_scroll_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],[disposable_0],([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_scroll_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this._AppComponent_0_4.context.onWindowScroll()) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import10.ComponentFactory<import0.AppComponent> = new import10.ComponentFactory<import0.AppComponent>('app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import11.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_7_4:import12.Wrapper_RouterLinkActive;
  _query_RouterLink_7_0:import13.QueryList<any>;
  _query_RouterLinkWithHref_7_1:import13.QueryList<any>;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _RouterLinkWithHref_10_3:import11.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_10_4:import12.Wrapper_RouterLinkActive;
  _query_RouterLink_10_0:import13.QueryList<any>;
  _query_RouterLinkWithHref_10_1:import13.QueryList<any>;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _RouterLinkWithHref_23_3:import11.Wrapper_RouterLinkWithHref;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _RouterLinkWithHref_26_3:import11.Wrapper_RouterLinkWithHref;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _RouterLinkWithHref_30_3:import11.Wrapper_RouterLinkWithHref;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _RouterLinkWithHref_42_3:import11.Wrapper_RouterLinkWithHref;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _anchor_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _TemplateRef_46_5:any;
  _NgFor_46_6:import14.Wrapper_NgFor;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import3.AppElement;
  _RouterOutlet_51_5:import15.Wrapper_RouterOutlet;
  _text_52:any;
  _arr_70:any;
  _arr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  _arr_76:any;
  /*private*/ _expr_77:any;
  _arr_78:any;
  _arr_79:any;
  /*private*/ _expr_80:any;
  _arr_81:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_70 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_71 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_72 = import7.UNINITIALIZED;
    this._expr_73 = import7.UNINITIALIZED;
    this._expr_74 = import7.UNINITIALIZED;
    this._expr_75 = import7.UNINITIALIZED;
    this._arr_76 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_77 = import7.UNINITIALIZED;
    this._arr_78 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_79 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_80 = import7.UNINITIALIZED;
    this._arr_81 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'header',new import4.InlineArray2(2,'id','header'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'div',new import4.InlineArray2(2,'class','headerNav'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'a',new import4.InlineArray2(2,'routerLinkActive','headerNavActive'),(null as any));
    this._RouterLinkWithHref_7_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._RouterLinkActive_7_4 = new import12.Wrapper_RouterLinkActive(this.parentInjector.get(import16.Router),new import19.ElementRef(this._el_7),this.renderer);
    this._query_RouterLink_7_0 = new import13.QueryList<any>();
    this._query_RouterLinkWithHref_7_1 = new import13.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'BLOG',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_5,'a',new import4.InlineArray2(2,'routerLinkActive','headerNavActive'),(null as any));
    this._RouterLinkWithHref_10_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._RouterLinkActive_10_4 = new import12.Wrapper_RouterLinkActive(this.parentInjector.get(import16.Router),new import19.ElementRef(this._el_10),this.renderer);
    this._query_RouterLink_10_0 = new import13.QueryList<any>();
    this._query_RouterLinkWithHref_10_1 = new import13.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'ABOUT',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_5,'a',new import4.InlineArray2(2,'target','_blank'),(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_13,'img',new import4.InlineArray2(2,'alt','facebook'),(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_5,'a',new import4.InlineArray2(2,'target','_blank'),(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_16,'img',new import4.InlineArray2(2,'alt','instagram'),(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_21 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'class','about-trigger'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_21,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_23_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_23,'img',new import4.InlineArray2(2,'alt','Linh Hoo'),(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_21,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_26_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_26,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'LINH HOO',(null as any));
    this._text_29 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_21,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_30_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_30,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Web/Mobile Developer',(null as any));
    this._text_33 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n    \n    ',(null as any));
    this._el_36 = import4.createRenderElement(this.renderer,parentRenderNode,'nav',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._el_38 = import4.createRenderElement(this.renderer,this._el_36,'div',new import4.InlineArray2(2,'class','scrolly-hidebar'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n            ',(null as any));
    this._el_40 = import4.createRenderElement(this.renderer,this._el_38,'div',new import4.InlineArray2(2,'style','width: 5000px;'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._el_42 = import4.createRenderElement(this.renderer,this._el_40,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._RouterLinkWithHref_42_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import16.Router),this.parentInjector.get(import17.ActivatedRoute),this.parentInjector.get(import18.LocationStrategy));
    this._el_43 = import4.createRenderElement(this.renderer,this._el_42,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Tất cả',(null as any));
    this._text_45 = this.renderer.createText(this._el_40,'\n                ',(null as any));
    this._anchor_46 = this.renderer.createTemplateAnchor(this._el_40,(null as any));
    this._appEl_46 = new import3.AppElement(46,40,this,this._anchor_46);
    this._TemplateRef_46_5 = new import20.TemplateRef_(this._appEl_46,viewFactory_AppComponent1);
    this._NgFor_46_6 = new import14.Wrapper_NgFor(this._appEl_46.vcRef,this._TemplateRef_46_5,this.parentInjector.get(import21.IterableDiffers),this.ref);
    this._text_47 = this.renderer.createText(this._el_40,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(parentRenderNode,'\n      ',(null as any));
    this._el_51 = import4.createRenderElement(this.renderer,parentRenderNode,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_51 = new import3.AppElement(51,(null as any),this,this._el_51);
    this._RouterOutlet_51_5 = new import15.Wrapper_RouterOutlet(this.parentInjector.get(import22.RouterOutletMap),this._appEl_51.vcRef,this.parentInjector.get(import23.ComponentFactoryResolver),(null as any));
    this._text_52 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._anchor_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3.context; }
    if (((token === import25.RouterLinkActive) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkActive_7_4.context; }
    if (((token === import24.RouterLinkWithHref) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkWithHref_10_3.context; }
    if (((token === import25.RouterLinkActive) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterLinkActive_10_4.context; }
    if (((token === import24.RouterLinkWithHref) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkWithHref_23_3.context; }
    if (((token === import24.RouterLinkWithHref) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkWithHref_26_3.context; }
    if (((token === import24.RouterLinkWithHref) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._RouterLinkWithHref_30_3.context; }
    if (((token === import24.RouterLinkWithHref) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._RouterLinkWithHref_42_3.context; }
    if (((token === import20.TemplateRef) && (46 === requestNodeIndex))) { return this._TemplateRef_46_5; }
    if (((token === import26.NgFor) && (46 === requestNodeIndex))) { return this._NgFor_46_6.context; }
    if (((token === import27.RouterOutlet) && (51 === requestNodeIndex))) { return this._RouterOutlet_51_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7_0_0:any = this._arr_70('blog');
    this._RouterLinkWithHref_7_3.check_routerLink(currVal_7_0_0,throwOnChange,false);
    this._RouterLinkWithHref_7_3.detectChangesInInputProps(this,this._el_7,throwOnChange);
    const currVal_7_1_0:any = 'headerNavActive';
    this._RouterLinkActive_7_4.check_routerLinkActive(currVal_7_1_0,throwOnChange,false);
    this._RouterLinkActive_7_4.detectChangesInInputProps(this,this._el_7,throwOnChange);
    const currVal_10_0_0:any = this._arr_71('about');
    this._RouterLinkWithHref_10_3.check_routerLink(currVal_10_0_0,throwOnChange,false);
    this._RouterLinkWithHref_10_3.detectChangesInInputProps(this,this._el_10,throwOnChange);
    const currVal_10_1_0:any = 'headerNavActive';
    this._RouterLinkActive_10_4.check_routerLinkActive(currVal_10_1_0,throwOnChange,false);
    this._RouterLinkActive_10_4.detectChangesInInputProps(this,this._el_10,throwOnChange);
    const currVal_23_0_0:any = this._arr_76('blog');
    this._RouterLinkWithHref_23_3.check_routerLink(currVal_23_0_0,throwOnChange,false);
    this._RouterLinkWithHref_23_3.detectChangesInInputProps(this,this._el_23,throwOnChange);
    const currVal_26_0_0:any = this._arr_78('blog');
    this._RouterLinkWithHref_26_3.check_routerLink(currVal_26_0_0,throwOnChange,false);
    this._RouterLinkWithHref_26_3.detectChangesInInputProps(this,this._el_26,throwOnChange);
    const currVal_30_0_0:any = this._arr_79('blog');
    this._RouterLinkWithHref_30_3.check_routerLink(currVal_30_0_0,throwOnChange,false);
    this._RouterLinkWithHref_30_3.detectChangesInInputProps(this,this._el_30,throwOnChange);
    const currVal_42_0_0:any = this._arr_81('blog');
    this._RouterLinkWithHref_42_3.check_routerLink(currVal_42_0_0,throwOnChange,false);
    this._RouterLinkWithHref_42_3.detectChangesInInputProps(this,this._el_42,throwOnChange);
    const currVal_46_0_0:any = this.context.menus;
    this._NgFor_46_6.check_ngForOf(currVal_46_0_0,throwOnChange,false);
    this._NgFor_46_6.detectChangesInInputProps(this,this._anchor_46,throwOnChange);
    this._RouterOutlet_51_5.detectChangesInInputProps(this,this._el_51,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_7_0.dirty) {
        this._query_RouterLink_7_0.reset(([] as any[]));
        this._RouterLinkActive_7_4.context.links = this._query_RouterLink_7_0;
        this._query_RouterLink_7_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_7_1.dirty) {
        this._query_RouterLinkWithHref_7_1.reset([this._RouterLinkWithHref_7_3.context]);
        this._RouterLinkActive_7_4.context.linksWithHrefs = this._query_RouterLinkWithHref_7_1;
        this._query_RouterLinkWithHref_7_1.notifyOnChanges();
      }
      if (this._query_RouterLink_10_0.dirty) {
        this._query_RouterLink_10_0.reset(([] as any[]));
        this._RouterLinkActive_10_4.context.links = this._query_RouterLink_10_0;
        this._query_RouterLink_10_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_10_1.dirty) {
        this._query_RouterLinkWithHref_10_1.reset([this._RouterLinkWithHref_10_3.context]);
        this._RouterLinkActive_10_4.context.linksWithHrefs = this._query_RouterLinkWithHref_10_1;
        this._query_RouterLinkWithHref_10_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_7_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_10_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_7_3.detectChangesInHostProps(this,this._el_7,throwOnChange);
    this._RouterLinkActive_7_4.detectChangesInHostProps(this,this._el_7,throwOnChange);
    this._RouterLinkWithHref_10_3.detectChangesInHostProps(this,this._el_10,throwOnChange);
    this._RouterLinkActive_10_4.detectChangesInHostProps(this,this._el_10,throwOnChange);
    const currVal_72:any = this.context.faceLink;
    if (import4.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementProperty(this._el_13,'href',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_72));
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = this.context.faceIcon;
    if (import4.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementProperty(this._el_14,'src',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_73));
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = this.context.instaLink;
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementProperty(this._el_16,'href',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_74));
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = this.context.instaIcon;
    if (import4.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setElementProperty(this._el_17,'src',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_75));
      this._expr_75 = currVal_75;
    }
    this._RouterLinkWithHref_23_3.detectChangesInHostProps(this,this._el_23,throwOnChange);
    const currVal_77:any = this.context.logo;
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setElementProperty(this._el_24,'src',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_77));
      this._expr_77 = currVal_77;
    }
    this._RouterLinkWithHref_26_3.detectChangesInHostProps(this,this._el_26,throwOnChange);
    this._RouterLinkWithHref_30_3.detectChangesInHostProps(this,this._el_30,throwOnChange);
    const currVal_80:any = this.context.navIsFixed;
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementClass(this._el_36,'fixed',currVal_80);
      this._expr_80 = currVal_80;
    }
    this._RouterLinkWithHref_42_3.detectChangesInHostProps(this,this._el_42,throwOnChange);
    this._RouterOutlet_51_5.detectChangesInHostProps(this,this._el_51,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_7_3.context.ngOnDestroy();
    this._RouterLinkActive_7_4.context.ngOnDestroy();
    this._RouterLinkWithHref_10_3.context.ngOnDestroy();
    this._RouterLinkActive_10_4.context.ngOnDestroy();
    this._RouterLinkWithHref_23_3.context.ngOnDestroy();
    this._RouterLinkWithHref_26_3.context.ngOnDestroy();
    this._RouterLinkWithHref_30_3.context.ngOnDestroy();
    this._RouterLinkWithHref_42_3.context.ngOnDestroy();
    this._RouterOutlet_51_5.context.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_7_0:any = ((<any>this._RouterLinkWithHref_7_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_7_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_10_0:any = ((<any>this._RouterLinkWithHref_10_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_10_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_23_0:any = ((<any>this._RouterLinkWithHref_23_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_23_0);
  }
  private _handle_click_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_26_0:any = ((<any>this._RouterLinkWithHref_26_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_26_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_30_0:any = ((<any>this._RouterLinkWithHref_30_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_30_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_42_0:any = ((<any>this._RouterLinkWithHref_42_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_42_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import11.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_0_4:import12.Wrapper_RouterLinkActive;
  _query_RouterLink_0_0:import13.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import13.QueryList<any>;
  _el_1:any;
  _text_2:any;
  _arr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent1,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._arr_7 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this._expr_8 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'a',new import4.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_0_3 = new import11.Wrapper_RouterLinkWithHref(this.parent.parentInjector.get(import16.Router),this.parent.parentInjector.get(import17.ActivatedRoute),this.parent.parentInjector.get(import18.LocationStrategy));
    this._RouterLinkActive_0_4 = new import12.Wrapper_RouterLinkActive(this.parent.parentInjector.get(import16.Router),new import19.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import13.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import13.QueryList<any>();
    this._el_1 = import4.createRenderElement(this.renderer,this._el_0,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkWithHref_0_3.context; }
    if (((token === import25.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RouterLinkActive_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this._arr_7('blog',this.context.$implicit.id,this.context.$implicit.slug);
    this._RouterLinkWithHref_0_3.check_routerLink(currVal_0_0_0,throwOnChange,false);
    this._RouterLinkWithHref_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    const currVal_0_1_0:any = 'active';
    this._RouterLinkActive_0_4.check_routerLinkActive(currVal_0_1_0,throwOnChange,false);
    this._RouterLinkActive_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset(([] as any[]));
        this._RouterLinkActive_0_4.context.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_0_3.context]);
        this._RouterLinkActive_0_4.context.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._RouterLinkActive_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    const currVal_8:any = import4.interpolate(1,'',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.name),'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_2,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.context.ngOnDestroy();
    this._RouterLinkActive_0_4.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this._RouterLinkWithHref_0_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_AppComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AppComponent1(viewUtils,parentInjector,declarationEl);
}