/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './browser.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import7 from 'angular2-universal/browser/universal-module';
import * as import8 from '@angular/forms/src/directives';
import * as import9 from '@angular/forms/src/form_providers';
import * as import10 from '@angular/router/src/router_module';
import * as import11 from '@angularclass/idle-preload/dist/index';
import * as import12 from './+app/shared/shared.module';
import * as import13 from './+app/+home/home-routing.module';
import * as import14 from './+app/+post/post.module';
import * as import15 from './+app/+postDetail/postDetail.module';
import * as import16 from './+app/+home/home.module';
import * as import17 from './+app/+about/about-routing.module';
import * as import18 from './+app/+about/about.module';
import * as import19 from './+app/+search/search-routing.module';
import * as import20 from './+app/+search/search.module';
import * as import21 from './+app/app-routing.module';
import * as import22 from './+app/app.module';
import * as import23 from './+app/shared/cache.service';
import * as import24 from '@angular/common/src/localization';
import * as import25 from '@angular/core/src/application_init';
import * as import26 from '@angular/core/src/testability/testability';
import * as import27 from '@angular/core/src/application_ref';
import * as import28 from '@angular/core/src/linker/compiler';
import * as import29 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import30 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import31 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import32 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import33 from '@angular/core/src/linker/view_utils';
import * as import34 from '@angular/platform-browser/src/browser/title';
import * as import35 from '@angular/http/src/backends/browser_xhr';
import * as import36 from '@angular/http/src/base_response_options';
import * as import37 from '@angular/http/src/backends/xhr_backend';
import * as import38 from '@angular/http/src/base_request_options';
import * as import39 from '@angular/http/src/backends/browser_jsonp';
import * as import40 from '@angular/http/src/backends/jsonp_backend';
import * as import41 from '@angular/router/src/url_tree';
import * as import42 from '@angular/router/src/router_outlet_map';
import * as import43 from '@angular/common/src/location/location';
import * as import44 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import45 from '@angular/router/src/router_preloader';
import * as import46 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import47 from '@angular/forms/src/form_builder';
import * as import48 from './+app/shared/api.service';
import * as import49 from './+app/shared/model/model.service';
import * as import50 from './angular2-meta';
import * as import51 from '@angular/core/src/di/injector';
import * as import52 from './+app/+home/home.component.ngfactory';
import * as import53 from './+app/+about/about.component.ngfactory';
import * as import54 from './+app/+search/search.component.ngfactory';
import * as import55 from './+app/app.component.ngfactory';
import * as import56 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import57 from '@angular/platform-browser/src/dom/events/key_events';
import * as import58 from '@angular/core/src/zone/ng_zone';
import * as import59 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import60 from '@angular/common/src/location/platform_location';
import * as import61 from '@angular/common/src/location/location_strategy';
import * as import62 from './+app/+home/home.component';
import * as import63 from './+app/+about/about.component';
import * as import64 from './+app/+search/search.component';
import * as import65 from 'angular2-universal/browser/env';
import * as import66 from '@angular/router/src/router';
import * as import67 from '@angular/core/src/console';
import * as import68 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import69 from '@angular/core/src/i18n/tokens';
import * as import70 from '@angular/core/src/error_handler';
import * as import71 from '@angular/core/src/application_tokens';
import * as import72 from '@angular/platform-browser/src/dom/animation_driver';
import * as import73 from '@angular/core/src/render/api';
import * as import74 from '@angular/core/src/security';
import * as import75 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import76 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import77 from '@angular/http/src/interfaces';
import * as import78 from '@angular/http/src/http';
import * as import79 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import80 from '@angular/router/src/router_config_loader';
import * as import81 from '@angular/router/src/router_state';
class MainModuleInjector extends import0.NgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _JsonpModule_4:import5.JsonpModule;
  _DOCUMENT_5:any;
  _DomSharedStylesHost_6:import6.DomSharedStylesHost;
  _SharedStylesHost_7:any;
  _UniversalModule_8:import7.UniversalModule;
  _InternalFormsSharedModule_9:import8.InternalFormsSharedModule;
  _FormsModule_10:import9.FormsModule;
  _ROUTER_FORROOT_GUARD_11:any;
  _RouterModule_12:import10.RouterModule;
  _IdlePreloadModule_13:import11.IdlePreloadModule;
  _ReactiveFormsModule_14:import9.ReactiveFormsModule;
  _SharedModule_15:import12.SharedModule;
  _HomeRoutingModule_16:import13.HomeRoutingModule;
  _PostModule_17:import14.PostModule;
  _PostDetailModule_18:import15.PostDetailModule;
  _HomeModule_19:import16.HomeModule;
  _AboutRoutingModule_20:import17.AboutRoutingModule;
  _AboutModule_21:import18.AboutModule;
  _SearchRoutingModule_22:import19.SearchRoutingModule;
  _SearchModule_23:import20.SearchModule;
  _AppRoutingModule_24:import21.AppRoutingModule;
  _AppModule_25:import22.AppModule;
  _LRU_26:any;
  _CacheService_27:import23.CacheService;
  _MainModule_28:import1.MainModule;
  __LOCALE_ID_29:any;
  __NgLocalization_30:import24.NgLocaleLocalization;
  _ErrorHandler_31:any;
  _ApplicationInitStatus_32:import25.ApplicationInitStatus;
  _Testability_33:import26.Testability;
  _ApplicationRef__34:import27.ApplicationRef_;
  __ApplicationRef_35:any;
  __Compiler_36:import28.Compiler;
  __APP_ID_37:any;
  __HAMMER_GESTURE_CONFIG_38:import29.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_39:any[];
  __EventManager_40:import30.EventManager;
  __AnimationDriver_41:any;
  __DomRootRenderer_42:import31.DomRootRenderer_;
  __RootRenderer_43:any;
  __DomSanitizer_44:import32.DomSanitizerImpl;
  __Sanitizer_45:any;
  __ViewUtils_46:import33.ViewUtils;
  __IterableDiffers_47:any;
  __KeyValueDiffers_48:any;
  __Title_49:import34.Title;
  __BrowserXhr_50:import35.BrowserXhr;
  __ResponseOptions_51:import36.BaseResponseOptions;
  __XSRFStrategy_52:any;
  __XHRBackend_53:import37.XHRBackend;
  __RequestOptions_54:import38.BaseRequestOptions;
  __Http_55:any;
  __BrowserJsonp_56:import39.BrowserJsonp;
  __JSONPBackend_57:import40.JSONPBackend_;
  __Jsonp_58:any;
  __UNIVERSAL_CACHE_59:any;
  __AUTO_PREBOOT_60:any;
  __UrlSerializer_61:import41.DefaultUrlSerializer;
  __RouterOutletMap_62:import42.RouterOutletMap;
  __ROUTER_CONFIGURATION_63:any;
  __LocationStrategy_64:any;
  __Location_65:import43.Location;
  __NgModuleFactoryLoader_66:import44.SystemJsNgModuleLoader;
  __ROUTES_67:any[];
  __Router_68:any;
  __REQUEST_IDLE_CALLBACK_69:any;
  __IdlePreload_70:import11.IdlePreload;
  __PreloadingStrategy_71:any;
  _RouterPreloader_72:import45.RouterPreloader;
  __APP_BOOTSTRAP_LISTENER_73:any[];
  __RadioControlRegistry_74:import46.RadioControlRegistry;
  __FormBuilder_75:import47.FormBuilder;
  __ActivatedRoute_76:any;
  __NoPreloading_77:import45.NoPreloading;
  __PreloadAllModules_78:import45.PreloadAllModules;
  __ApiService_79:import48.ApiService;
  __ModelService_80:import49.ModelService;
  __isBrowser_81:any;
  __isNode_82:any;
  __req_83:any;
  __res_84:any;
  __Meta_85:import50.Meta;
  constructor(parent:import51.Injector) {
    super(parent,[
      import52.HomeComponentNgFactory,
      import52.HomeComponentNgFactory,
      import52.HomeComponentNgFactory,
      import53.AboutComponentNgFactory,
      import54.SearchComponentNgFactory,
      import55.AppComponentNgFactory
    ]
    ,[import55.AppComponentNgFactory]);
  }
  get _LOCALE_ID_29():any {
    if ((this.__LOCALE_ID_29 == (null as any))) { (this.__LOCALE_ID_29 = 'en-US'); }
    return this.__LOCALE_ID_29;
  }
  get _NgLocalization_30():import24.NgLocaleLocalization {
    if ((this.__NgLocalization_30 == (null as any))) { (this.__NgLocalization_30 = new import24.NgLocaleLocalization(this._LOCALE_ID_29)); }
    return this.__NgLocalization_30;
  }
  get _ApplicationRef_35():any {
    if ((this.__ApplicationRef_35 == (null as any))) { (this.__ApplicationRef_35 = this._ApplicationRef__34); }
    return this.__ApplicationRef_35;
  }
  get _Compiler_36():import28.Compiler {
    if ((this.__Compiler_36 == (null as any))) { (this.__Compiler_36 = new import28.Compiler()); }
    return this.__Compiler_36;
  }
  get _APP_ID_37():any {
    if ((this.__APP_ID_37 == (null as any))) { (this.__APP_ID_37 = import7.appIdFactory()); }
    return this.__APP_ID_37;
  }
  get _HAMMER_GESTURE_CONFIG_38():import29.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_38 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_38 = new import29.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_38;
  }
  get _EVENT_MANAGER_PLUGINS_39():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_39 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_39 = [
      new import56.DomEventsPlugin(),
      new import57.KeyEventsPlugin(),
      new import29.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_38)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_39;
  }
  get _EventManager_40():import30.EventManager {
    if ((this.__EventManager_40 == (null as any))) { (this.__EventManager_40 = new import30.EventManager(this._EVENT_MANAGER_PLUGINS_39,this.parent.get(import58.NgZone))); }
    return this.__EventManager_40;
  }
  get _AnimationDriver_41():any {
    if ((this.__AnimationDriver_41 == (null as any))) { (this.__AnimationDriver_41 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_41;
  }
  get _DomRootRenderer_42():import31.DomRootRenderer_ {
    if ((this.__DomRootRenderer_42 == (null as any))) { (this.__DomRootRenderer_42 = new import31.DomRootRenderer_(this._DOCUMENT_5,this._EventManager_40,this._DomSharedStylesHost_6,this._AnimationDriver_41)); }
    return this.__DomRootRenderer_42;
  }
  get _RootRenderer_43():any {
    if ((this.__RootRenderer_43 == (null as any))) { (this.__RootRenderer_43 = import59._createConditionalRootRenderer(this._DomRootRenderer_42,this.parent.get(import59.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_43;
  }
  get _DomSanitizer_44():import32.DomSanitizerImpl {
    if ((this.__DomSanitizer_44 == (null as any))) { (this.__DomSanitizer_44 = new import32.DomSanitizerImpl()); }
    return this.__DomSanitizer_44;
  }
  get _Sanitizer_45():any {
    if ((this.__Sanitizer_45 == (null as any))) { (this.__Sanitizer_45 = this._DomSanitizer_44); }
    return this.__Sanitizer_45;
  }
  get _ViewUtils_46():import33.ViewUtils {
    if ((this.__ViewUtils_46 == (null as any))) { (this.__ViewUtils_46 = new import33.ViewUtils(this._RootRenderer_43,this._APP_ID_37,this._Sanitizer_45)); }
    return this.__ViewUtils_46;
  }
  get _IterableDiffers_47():any {
    if ((this.__IterableDiffers_47 == (null as any))) { (this.__IterableDiffers_47 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_47;
  }
  get _KeyValueDiffers_48():any {
    if ((this.__KeyValueDiffers_48 == (null as any))) { (this.__KeyValueDiffers_48 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_48;
  }
  get _Title_49():import34.Title {
    if ((this.__Title_49 == (null as any))) { (this.__Title_49 = new import34.Title()); }
    return this.__Title_49;
  }
  get _BrowserXhr_50():import35.BrowserXhr {
    if ((this.__BrowserXhr_50 == (null as any))) { (this.__BrowserXhr_50 = new import35.BrowserXhr()); }
    return this.__BrowserXhr_50;
  }
  get _ResponseOptions_51():import36.BaseResponseOptions {
    if ((this.__ResponseOptions_51 == (null as any))) { (this.__ResponseOptions_51 = new import36.BaseResponseOptions()); }
    return this.__ResponseOptions_51;
  }
  get _XSRFStrategy_52():any {
    if ((this.__XSRFStrategy_52 == (null as any))) { (this.__XSRFStrategy_52 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_52;
  }
  get _XHRBackend_53():import37.XHRBackend {
    if ((this.__XHRBackend_53 == (null as any))) { (this.__XHRBackend_53 = new import37.XHRBackend(this._BrowserXhr_50,this._ResponseOptions_51,this._XSRFStrategy_52)); }
    return this.__XHRBackend_53;
  }
  get _RequestOptions_54():import38.BaseRequestOptions {
    if ((this.__RequestOptions_54 == (null as any))) { (this.__RequestOptions_54 = new import38.BaseRequestOptions()); }
    return this.__RequestOptions_54;
  }
  get _Http_55():any {
    if ((this.__Http_55 == (null as any))) { (this.__Http_55 = import5.httpFactory(this._XHRBackend_53,this._RequestOptions_54)); }
    return this.__Http_55;
  }
  get _BrowserJsonp_56():import39.BrowserJsonp {
    if ((this.__BrowserJsonp_56 == (null as any))) { (this.__BrowserJsonp_56 = new import39.BrowserJsonp()); }
    return this.__BrowserJsonp_56;
  }
  get _JSONPBackend_57():import40.JSONPBackend_ {
    if ((this.__JSONPBackend_57 == (null as any))) { (this.__JSONPBackend_57 = new import40.JSONPBackend_(this._BrowserJsonp_56,this._ResponseOptions_51)); }
    return this.__JSONPBackend_57;
  }
  get _Jsonp_58():any {
    if ((this.__Jsonp_58 == (null as any))) { (this.__Jsonp_58 = import5.jsonpFactory(this._JSONPBackend_57,this._RequestOptions_54)); }
    return this.__Jsonp_58;
  }
  get _UNIVERSAL_CACHE_59():any {
    if ((this.__UNIVERSAL_CACHE_59 == (null as any))) { (this.__UNIVERSAL_CACHE_59 = import7.universalCacheFactory()); }
    return this.__UNIVERSAL_CACHE_59;
  }
  get _AUTO_PREBOOT_60():any {
    if ((this.__AUTO_PREBOOT_60 == (null as any))) { (this.__AUTO_PREBOOT_60 = true); }
    return this.__AUTO_PREBOOT_60;
  }
  get _UrlSerializer_61():import41.DefaultUrlSerializer {
    if ((this.__UrlSerializer_61 == (null as any))) { (this.__UrlSerializer_61 = new import41.DefaultUrlSerializer()); }
    return this.__UrlSerializer_61;
  }
  get _RouterOutletMap_62():import42.RouterOutletMap {
    if ((this.__RouterOutletMap_62 == (null as any))) { (this.__RouterOutletMap_62 = new import42.RouterOutletMap()); }
    return this.__RouterOutletMap_62;
  }
  get _ROUTER_CONFIGURATION_63():any {
    if ((this.__ROUTER_CONFIGURATION_63 == (null as any))) { (this.__ROUTER_CONFIGURATION_63 = {
      useHash: false,
      preloadingStrategy: import11.IdlePreload
    }
    ); }
    return this.__ROUTER_CONFIGURATION_63;
  }
  get _LocationStrategy_64():any {
    if ((this.__LocationStrategy_64 == (null as any))) { (this.__LocationStrategy_64 = import10.provideLocationStrategy(this.parent.get(import60.PlatformLocation),this.parent.get(import61.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_63)); }
    return this.__LocationStrategy_64;
  }
  get _Location_65():import43.Location {
    if ((this.__Location_65 == (null as any))) { (this.__Location_65 = new import43.Location(this._LocationStrategy_64)); }
    return this.__Location_65;
  }
  get _NgModuleFactoryLoader_66():import44.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_66 == (null as any))) { (this.__NgModuleFactoryLoader_66 = new import44.SystemJsNgModuleLoader(this._Compiler_36,this.parent.get(import44.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_66;
  }
  get _ROUTES_67():any[] {
    if ((this.__ROUTES_67 == (null as any))) { (this.__ROUTES_67 = [
      [
        {
          path: 'blog',
          component: import62.HomeComponent
        }
        ,
        {
          path: 'blog/:idCategory/:category',
          component: import62.HomeComponent
        }
        ,
        {
          path: 'blog/:idCategory/:idPost/:post',
          component: import62.HomeComponent
        }

      ]
      ,
        [{
          path: 'about',
          component: import63.AboutComponent
        }
      ],
        [{
          path: 'search',
          component: import64.SearchComponent
        }
      ],
        [{
          path: '',
          redirectTo: '/blog',
          pathMatch: 'full'
        }
      ],
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_67;
  }
  get _Router_68():any {
    if ((this.__Router_68 == (null as any))) { (this.__Router_68 = import10.setupRouter(this._ApplicationRef_35,this._UrlSerializer_61,this._RouterOutletMap_62,this._Location_65,this,this._NgModuleFactoryLoader_66,this._Compiler_36,this._ROUTES_67,this._ROUTER_CONFIGURATION_63)); }
    return this.__Router_68;
  }
  get _REQUEST_IDLE_CALLBACK_69():any {
    if ((this.__REQUEST_IDLE_CALLBACK_69 == (null as any))) { (this.__REQUEST_IDLE_CALLBACK_69 = import11._requestIdle(this.parent.get(import58.NgZone))); }
    return this.__REQUEST_IDLE_CALLBACK_69;
  }
  get _IdlePreload_70():import11.IdlePreload {
    if ((this.__IdlePreload_70 == (null as any))) { (this.__IdlePreload_70 = new import11.IdlePreload(this.parent.get(import58.NgZone),this._REQUEST_IDLE_CALLBACK_69)); }
    return this.__IdlePreload_70;
  }
  get _PreloadingStrategy_71():any {
    if ((this.__PreloadingStrategy_71 == (null as any))) { (this.__PreloadingStrategy_71 = this._IdlePreload_70); }
    return this.__PreloadingStrategy_71;
  }
  get _APP_BOOTSTRAP_LISTENER_73():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_73 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_73 = [
      import7.appBootstrapListenerFactory(this._AUTO_PREBOOT_60),
      import10.initialRouterNavigation(this._Router_68,this._ApplicationRef_35,this._RouterPreloader_72,this._ROUTER_CONFIGURATION_63)
    ]
    ); }
    return this.__APP_BOOTSTRAP_LISTENER_73;
  }
  get _RadioControlRegistry_74():import46.RadioControlRegistry {
    if ((this.__RadioControlRegistry_74 == (null as any))) { (this.__RadioControlRegistry_74 = new import46.RadioControlRegistry()); }
    return this.__RadioControlRegistry_74;
  }
  get _FormBuilder_75():import47.FormBuilder {
    if ((this.__FormBuilder_75 == (null as any))) { (this.__FormBuilder_75 = new import47.FormBuilder()); }
    return this.__FormBuilder_75;
  }
  get _ActivatedRoute_76():any {
    if ((this.__ActivatedRoute_76 == (null as any))) { (this.__ActivatedRoute_76 = import10.rootRoute(this._Router_68)); }
    return this.__ActivatedRoute_76;
  }
  get _NoPreloading_77():import45.NoPreloading {
    if ((this.__NoPreloading_77 == (null as any))) { (this.__NoPreloading_77 = new import45.NoPreloading()); }
    return this.__NoPreloading_77;
  }
  get _PreloadAllModules_78():import45.PreloadAllModules {
    if ((this.__PreloadAllModules_78 == (null as any))) { (this.__PreloadAllModules_78 = new import45.PreloadAllModules()); }
    return this.__PreloadAllModules_78;
  }
  get _ApiService_79():import48.ApiService {
    if ((this.__ApiService_79 == (null as any))) { (this.__ApiService_79 = new import48.ApiService(this._Http_55)); }
    return this.__ApiService_79;
  }
  get _ModelService_80():import49.ModelService {
    if ((this.__ModelService_80 == (null as any))) { (this.__ModelService_80 = new import49.ModelService(this._ApiService_79,this._CacheService_27)); }
    return this.__ModelService_80;
  }
  get _isBrowser_81():any {
    if ((this.__isBrowser_81 == (null as any))) { (this.__isBrowser_81 = true); }
    return this.__isBrowser_81;
  }
  get _isNode_82():any {
    if ((this.__isNode_82 == (null as any))) { (this.__isNode_82 = import65.isNode); }
    return this.__isNode_82;
  }
  get _req_83():any {
    if ((this.__req_83 == (null as any))) { (this.__req_83 = import1.getRequest()); }
    return this.__req_83;
  }
  get _res_84():any {
    if ((this.__res_84 == (null as any))) { (this.__res_84 = import1.getResponse()); }
    return this.__res_84;
  }
  get _Meta_85():import50.Meta {
    if ((this.__Meta_85 == (null as any))) { (this.__Meta_85 = new import50.Meta()); }
    return this.__Meta_85;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._JsonpModule_4 = new import5.JsonpModule();
    this._DOCUMENT_5 = import4._document();
    this._DomSharedStylesHost_6 = new import6.DomSharedStylesHost(this._DOCUMENT_5);
    this._SharedStylesHost_7 = this._DomSharedStylesHost_6;
    this._UniversalModule_8 = new import7.UniversalModule(this._SharedStylesHost_7);
    this._InternalFormsSharedModule_9 = new import8.InternalFormsSharedModule();
    this._FormsModule_10 = new import9.FormsModule();
    this._ROUTER_FORROOT_GUARD_11 = import10.provideForRootGuard(this.parent.get(import66.Router,(null as any)));
    this._RouterModule_12 = new import10.RouterModule(this._ROUTER_FORROOT_GUARD_11);
    this._IdlePreloadModule_13 = new import11.IdlePreloadModule();
    this._ReactiveFormsModule_14 = new import9.ReactiveFormsModule();
    this._SharedModule_15 = new import12.SharedModule();
    this._HomeRoutingModule_16 = new import13.HomeRoutingModule();
    this._PostModule_17 = new import14.PostModule();
    this._PostDetailModule_18 = new import15.PostDetailModule();
    this._HomeModule_19 = new import16.HomeModule();
    this._AboutRoutingModule_20 = new import17.AboutRoutingModule();
    this._AboutModule_21 = new import18.AboutModule();
    this._SearchRoutingModule_22 = new import19.SearchRoutingModule();
    this._SearchModule_23 = new import20.SearchModule();
    this._AppRoutingModule_24 = new import21.AppRoutingModule();
    this._AppModule_25 = new import22.AppModule();
    this._LRU_26 = import1.getLRU();
    this._CacheService_27 = new import23.CacheService(this._LRU_26);
    this._MainModule_28 = new import1.MainModule(this._CacheService_27);
    this._ErrorHandler_31 = import4.errorHandler();
    this._ApplicationInitStatus_32 = new import25.ApplicationInitStatus(this.parent.get(import25.APP_INITIALIZER,(null as any)));
    this._Testability_33 = new import26.Testability(this.parent.get(import58.NgZone));
    this._ApplicationRef__34 = new import27.ApplicationRef_(this.parent.get(import58.NgZone),this.parent.get(import67.Console),this,this._ErrorHandler_31,this,this._ApplicationInitStatus_32,this.parent.get(import26.TestabilityRegistry,(null as any)),this._Testability_33);
    this._RouterPreloader_72 = new import45.RouterPreloader(this._Router_68,this._NgModuleFactoryLoader_66,this._Compiler_36,this,this._PreloadingStrategy_71);
    return this._MainModule_28;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import5.JsonpModule)) { return this._JsonpModule_4; }
    if ((token === import68.DOCUMENT)) { return this._DOCUMENT_5; }
    if ((token === import6.DomSharedStylesHost)) { return this._DomSharedStylesHost_6; }
    if ((token === import6.SharedStylesHost)) { return this._SharedStylesHost_7; }
    if ((token === import7.UniversalModule)) { return this._UniversalModule_8; }
    if ((token === import8.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import9.FormsModule)) { return this._FormsModule_10; }
    if ((token === import10.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_11; }
    if ((token === import10.RouterModule)) { return this._RouterModule_12; }
    if ((token === import11.IdlePreloadModule)) { return this._IdlePreloadModule_13; }
    if ((token === import9.ReactiveFormsModule)) { return this._ReactiveFormsModule_14; }
    if ((token === import12.SharedModule)) { return this._SharedModule_15; }
    if ((token === import13.HomeRoutingModule)) { return this._HomeRoutingModule_16; }
    if ((token === import14.PostModule)) { return this._PostModule_17; }
    if ((token === import15.PostDetailModule)) { return this._PostDetailModule_18; }
    if ((token === import16.HomeModule)) { return this._HomeModule_19; }
    if ((token === import17.AboutRoutingModule)) { return this._AboutRoutingModule_20; }
    if ((token === import18.AboutModule)) { return this._AboutModule_21; }
    if ((token === import19.SearchRoutingModule)) { return this._SearchRoutingModule_22; }
    if ((token === import20.SearchModule)) { return this._SearchModule_23; }
    if ((token === import21.AppRoutingModule)) { return this._AppRoutingModule_24; }
    if ((token === import22.AppModule)) { return this._AppModule_25; }
    if ((token === 'LRU')) { return this._LRU_26; }
    if ((token === import23.CacheService)) { return this._CacheService_27; }
    if ((token === import1.MainModule)) { return this._MainModule_28; }
    if ((token === import69.LOCALE_ID)) { return this._LOCALE_ID_29; }
    if ((token === import24.NgLocalization)) { return this._NgLocalization_30; }
    if ((token === import70.ErrorHandler)) { return this._ErrorHandler_31; }
    if ((token === import25.ApplicationInitStatus)) { return this._ApplicationInitStatus_32; }
    if ((token === import26.Testability)) { return this._Testability_33; }
    if ((token === import27.ApplicationRef_)) { return this._ApplicationRef__34; }
    if ((token === import27.ApplicationRef)) { return this._ApplicationRef_35; }
    if ((token === import28.Compiler)) { return this._Compiler_36; }
    if ((token === import71.APP_ID)) { return this._APP_ID_37; }
    if ((token === import29.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_38; }
    if ((token === import30.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_39; }
    if ((token === import30.EventManager)) { return this._EventManager_40; }
    if ((token === import72.AnimationDriver)) { return this._AnimationDriver_41; }
    if ((token === import31.DomRootRenderer)) { return this._DomRootRenderer_42; }
    if ((token === import73.RootRenderer)) { return this._RootRenderer_43; }
    if ((token === import32.DomSanitizer)) { return this._DomSanitizer_44; }
    if ((token === import74.Sanitizer)) { return this._Sanitizer_45; }
    if ((token === import33.ViewUtils)) { return this._ViewUtils_46; }
    if ((token === import75.IterableDiffers)) { return this._IterableDiffers_47; }
    if ((token === import76.KeyValueDiffers)) { return this._KeyValueDiffers_48; }
    if ((token === import34.Title)) { return this._Title_49; }
    if ((token === import35.BrowserXhr)) { return this._BrowserXhr_50; }
    if ((token === import36.ResponseOptions)) { return this._ResponseOptions_51; }
    if ((token === import77.XSRFStrategy)) { return this._XSRFStrategy_52; }
    if ((token === import37.XHRBackend)) { return this._XHRBackend_53; }
    if ((token === import38.RequestOptions)) { return this._RequestOptions_54; }
    if ((token === import78.Http)) { return this._Http_55; }
    if ((token === import39.BrowserJsonp)) { return this._BrowserJsonp_56; }
    if ((token === import40.JSONPBackend)) { return this._JSONPBackend_57; }
    if ((token === import78.Jsonp)) { return this._Jsonp_58; }
    if ((token === import7.UNIVERSAL_CACHE)) { return this._UNIVERSAL_CACHE_59; }
    if ((token === import7.AUTO_PREBOOT)) { return this._AUTO_PREBOOT_60; }
    if ((token === import41.UrlSerializer)) { return this._UrlSerializer_61; }
    if ((token === import42.RouterOutletMap)) { return this._RouterOutletMap_62; }
    if ((token === import10.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_63; }
    if ((token === import61.LocationStrategy)) { return this._LocationStrategy_64; }
    if ((token === import43.Location)) { return this._Location_65; }
    if ((token === import79.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_66; }
    if ((token === import80.ROUTES)) { return this._ROUTES_67; }
    if ((token === import66.Router)) { return this._Router_68; }
    if ((token === import11.REQUEST_IDLE_CALLBACK)) { return this._REQUEST_IDLE_CALLBACK_69; }
    if ((token === import11.IdlePreload)) { return this._IdlePreload_70; }
    if ((token === import45.PreloadingStrategy)) { return this._PreloadingStrategy_71; }
    if ((token === import45.RouterPreloader)) { return this._RouterPreloader_72; }
    if ((token === import71.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_73; }
    if ((token === import46.RadioControlRegistry)) { return this._RadioControlRegistry_74; }
    if ((token === import47.FormBuilder)) { return this._FormBuilder_75; }
    if ((token === import81.ActivatedRoute)) { return this._ActivatedRoute_76; }
    if ((token === import45.NoPreloading)) { return this._NoPreloading_77; }
    if ((token === import45.PreloadAllModules)) { return this._PreloadAllModules_78; }
    if ((token === import48.ApiService)) { return this._ApiService_79; }
    if ((token === import49.ModelService)) { return this._ModelService_80; }
    if ((token === 'isBrowser')) { return this._isBrowser_81; }
    if ((token === 'isNode')) { return this._isNode_82; }
    if ((token === 'req')) { return this._req_83; }
    if ((token === 'res')) { return this._res_84; }
    if ((token === import50.Meta)) { return this._Meta_85; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__34.ngOnDestroy();
    this._RouterPreloader_72.ngOnDestroy();
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory(MainModuleInjector,import1.MainModule);