/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './node.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from 'angular2-platform-node/node-platform';
import * as import5 from 'angular2-platform-node/node-http';
import * as import6 from 'angular2-universal/node/universal-module';
import * as import7 from '@angular/forms/src/directives';
import * as import8 from '@angular/forms/src/form_providers';
import * as import9 from '@angular/router/src/router_module';
import * as import10 from './+app/shared/shared.module';
import * as import11 from './+app/+home/home-routing.module';
import * as import12 from './+app/+post/post.module';
import * as import13 from './+app/+postDetail/postDetail.module';
import * as import14 from '@angular/platform-browser/src/browser';
import * as import15 from './+app/+home/home.module';
import * as import16 from './+app/+about/about-routing.module';
import * as import17 from './+app/+about/about.module';
import * as import18 from './+app/app-routing.module';
import * as import19 from './+app/app.module';
import * as import20 from './+app/shared/cache.service';
import * as import21 from '@angular/common/src/localization';
import * as import22 from '@angular/core/src/application_init';
import * as import23 from '@angular/core/src/testability/testability';
import * as import24 from '@angular/core/src/application_ref';
import * as import25 from '@angular/core/src/linker/compiler';
import * as import26 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import27 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import28 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import29 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import30 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import31 from '@angular/core/src/linker/view_utils';
import * as import32 from 'angular2-platform-node/node-location';
import * as import33 from 'angular2-platform-node/node-shared-styles-host';
import * as import34 from 'angular2-platform-node/node-renderer';
import * as import35 from '@angular/http/src/base_request_options';
import * as import36 from '@angular/http/src/base_response_options';
import * as import37 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import38 from '@angular/forms/src/form_builder';
import * as import39 from '@angular/platform-browser/src/browser/title';
import * as import40 from '@angular/common/src/location/location';
import * as import41 from '@angular/router/src/url_tree';
import * as import42 from '@angular/router/src/router_outlet_map';
import * as import43 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import44 from '@angular/router/src/router_preloader';
import * as import45 from './+app/shared/api.service';
import * as import46 from './+app/shared/model/model.service';
import * as import47 from './angular2-meta';
import * as import48 from '@angular/core/src/di/injector';
import * as import49 from './+app/+home/home.component.ngfactory';
import * as import50 from './+app/+about/about.component.ngfactory';
import * as import51 from './+app/app.component.ngfactory';
import * as import52 from '@angular/platform-browser/src/dom/events/key_events';
import * as import53 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import54 from '@angular/core/src/zone/ng_zone';
import * as import55 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import56 from './+app/+home/home.component';
import * as import57 from './+app/+about/about.component';
import * as import58 from 'angular2-universal/node/env';
import * as import59 from '@angular/router/src/router';
import * as import60 from '@angular/core/src/console';
import * as import61 from '@angular/core/src/i18n/tokens';
import * as import62 from '@angular/core/src/error_handler';
import * as import63 from '@angular/core/src/application_tokens';
import * as import64 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import65 from '@angular/platform-browser/src/dom/animation_driver';
import * as import66 from '@angular/core/src/render/api';
import * as import67 from '@angular/core/src/security';
import * as import68 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import69 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import70 from 'angular2-platform-node/tokens';
import * as import71 from '@angular/common/src/location/location_strategy';
import * as import72 from '@angular/common/src/location/platform_location';
import * as import73 from '@angular/http/src/interfaces';
import * as import74 from '@angular/http/src/backends/browser_xhr';
import * as import75 from '@angular/http/src/backends/xhr_backend';
import * as import76 from '@angular/http/src/http';
import * as import77 from '@angular/http/src/backends/jsonp_backend';
import * as import78 from '@angular/router/src/router_config_loader';
import * as import79 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import80 from '@angular/router/src/router_state';
class MainModuleInjector extends import0.NgModuleInjector<import1.MainModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _NodeModule_2:import4.NodeModule;
  _NodeHttpModule_3:import5.NodeHttpModule;
  _NodeJsonpModule_4:import5.NodeJsonpModule;
  _UniversalModule_5:import6.UniversalModule;
  _InternalFormsSharedModule_6:import7.InternalFormsSharedModule;
  _FormsModule_7:import8.FormsModule;
  _ROUTER_FORROOT_GUARD_8:any;
  _RouterModule_9:import9.RouterModule;
  _ReactiveFormsModule_10:import8.ReactiveFormsModule;
  _SharedModule_11:import10.SharedModule;
  _HomeRoutingModule_12:import11.HomeRoutingModule;
  _PostModule_13:import12.PostModule;
  _PostDetailModule_14:import13.PostDetailModule;
  _BrowserModule_15:import14.BrowserModule;
  _HomeModule_16:import15.HomeModule;
  _AboutRoutingModule_17:import16.AboutRoutingModule;
  _AboutModule_18:import17.AboutModule;
  _AppRoutingModule_19:import18.AppRoutingModule;
  _AppModule_20:import19.AppModule;
  _LRU_21:any;
  _CacheService_22:import20.CacheService;
  _MainModule_23:import1.MainModule;
  __LOCALE_ID_24:any;
  __NgLocalization_25:import21.NgLocaleLocalization;
  _ErrorHandler_26:any;
  _ApplicationInitStatus_27:import22.ApplicationInitStatus;
  _TestabilityRegistry_28:import4.MockTestabilityRegistry;
  _Testability_29:import23.Testability;
  _ApplicationRef__30:import24.ApplicationRef_;
  __ApplicationRef_31:any;
  __Compiler_32:import25.Compiler;
  __APP_ID_33:any;
  __DOCUMENT_34:any;
  __NodeDomEventsPlugin_35:import4.NodeDomEventsPlugin;
  __HAMMER_GESTURE_CONFIG_36:import26.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_37:any[];
  __EventManager_38:import27.EventManager;
  __DomSharedStylesHost_39:import28.DomSharedStylesHost;
  __AnimationDriver_40:any;
  __DomRootRenderer_41:import29.DomRootRenderer_;
  __RootRenderer_42:any;
  __DomSanitizer_43:import30.DomSanitizerImpl;
  __Sanitizer_44:any;
  __ViewUtils_45:import31.ViewUtils;
  __IterableDiffers_46:any;
  __KeyValueDiffers_47:any;
  __ORIGIN_URL_48:any;
  __REQUEST_URL_49:any;
  __APP_BASE_HREF_50:any;
  __PlatformLocation_51:import32.NodePlatformLocation;
  __DomEventsPlugin_52:any[];
  __NodeEventManager_53:import4.NodeEventManager;
  __NodeSharedStylesHost_54:import33.NodeSharedStylesHost;
  __NodeDomRootRenderer_55:import34.NodeDomRootRenderer;
  __SharedStylesHost_56:any;
  __XSRFStrategy_57:any;
  __BrowserXhr_58:any;
  __RequestOptions_59:import35.BaseRequestOptions;
  __ResponseOptions_60:import36.BaseResponseOptions;
  __XHRBackend_61:import5.NodeBackend;
  __Http_62:any;
  __JSONPBackend_63:import5.NodeJsonpBackend_;
  __Jsonp_64:any;
  __RadioControlRegistry_65:import37.RadioControlRegistry;
  __FormBuilder_66:import38.FormBuilder;
  __ROUTES_67:any[];
  __Title_68:import39.Title;
  __ROUTER_CONFIGURATION_69:any;
  __LocationStrategy_70:any;
  __Location_71:import40.Location;
  __UrlSerializer_72:import41.DefaultUrlSerializer;
  __RouterOutletMap_73:import42.RouterOutletMap;
  __NgModuleFactoryLoader_74:import43.SystemJsNgModuleLoader;
  __Router_75:any;
  __ActivatedRoute_76:any;
  _NoPreloading_77:import44.NoPreloading;
  _PreloadingStrategy_78:any;
  _RouterPreloader_79:import44.RouterPreloader;
  __PreloadAllModules_80:import44.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_81:any[];
  __ApiService_82:import45.ApiService;
  __ModelService_83:import46.ModelService;
  __isBrowser_84:any;
  __isNode_85:any;
  __req_86:any;
  __res_87:any;
  __Meta_88:import47.Meta;
  constructor(parent:import48.Injector) {
    super(parent,[
      import49.HomeComponentNgFactory,
      import49.HomeComponentNgFactory,
      import49.HomeComponentNgFactory,
      import50.AboutComponentNgFactory,
      import51.AppComponentNgFactory
    ]
    ,[import51.AppComponentNgFactory]);
  }
  get _LOCALE_ID_24():any {
    if ((this.__LOCALE_ID_24 == (null as any))) { (this.__LOCALE_ID_24 = 'en-US'); }
    return this.__LOCALE_ID_24;
  }
  get _NgLocalization_25():import21.NgLocaleLocalization {
    if ((this.__NgLocalization_25 == (null as any))) { (this.__NgLocalization_25 = new import21.NgLocaleLocalization(this._LOCALE_ID_24)); }
    return this.__NgLocalization_25;
  }
  get _ApplicationRef_31():any {
    if ((this.__ApplicationRef_31 == (null as any))) { (this.__ApplicationRef_31 = this._ApplicationRef__30); }
    return this.__ApplicationRef_31;
  }
  get _Compiler_32():import25.Compiler {
    if ((this.__Compiler_32 == (null as any))) { (this.__Compiler_32 = new import25.Compiler()); }
    return this.__Compiler_32;
  }
  get _APP_ID_33():any {
    if ((this.__APP_ID_33 == (null as any))) { (this.__APP_ID_33 = '%cmp%'); }
    return this.__APP_ID_33;
  }
  get _DOCUMENT_34():any {
    if ((this.__DOCUMENT_34 == (null as any))) { (this.__DOCUMENT_34 = import14._document()); }
    return this.__DOCUMENT_34;
  }
  get _NodeDomEventsPlugin_35():import4.NodeDomEventsPlugin {
    if ((this.__NodeDomEventsPlugin_35 == (null as any))) { (this.__NodeDomEventsPlugin_35 = new import4.NodeDomEventsPlugin()); }
    return this.__NodeDomEventsPlugin_35;
  }
  get _HAMMER_GESTURE_CONFIG_36():import26.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_36 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_36 = new import26.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_36;
  }
  get _EVENT_MANAGER_PLUGINS_37():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_37 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_37 = [
      this._NodeDomEventsPlugin_35,
      new import52.KeyEventsPlugin(),
      new import26.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_36),
      new import53.DomEventsPlugin(),
      new import52.KeyEventsPlugin(),
      new import26.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_36)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_37;
  }
  get _EventManager_38():import27.EventManager {
    if ((this.__EventManager_38 == (null as any))) { (this.__EventManager_38 = new import27.EventManager(this._EVENT_MANAGER_PLUGINS_37,this.parent.get(import54.NgZone))); }
    return this.__EventManager_38;
  }
  get _DomSharedStylesHost_39():import28.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_39 == (null as any))) { (this.__DomSharedStylesHost_39 = new import28.DomSharedStylesHost(this._DOCUMENT_34)); }
    return this.__DomSharedStylesHost_39;
  }
  get _AnimationDriver_40():any {
    if ((this.__AnimationDriver_40 == (null as any))) { (this.__AnimationDriver_40 = import14._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_40;
  }
  get _DomRootRenderer_41():import29.DomRootRenderer_ {
    if ((this.__DomRootRenderer_41 == (null as any))) { (this.__DomRootRenderer_41 = new import29.DomRootRenderer_(this._DOCUMENT_34,this._EventManager_38,this._DomSharedStylesHost_39,this._AnimationDriver_40)); }
    return this.__DomRootRenderer_41;
  }
  get _RootRenderer_42():any {
    if ((this.__RootRenderer_42 == (null as any))) { (this.__RootRenderer_42 = import55._createConditionalRootRenderer(this._DomRootRenderer_41,this.parent.get(import55.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_42;
  }
  get _DomSanitizer_43():import30.DomSanitizerImpl {
    if ((this.__DomSanitizer_43 == (null as any))) { (this.__DomSanitizer_43 = new import30.DomSanitizerImpl()); }
    return this.__DomSanitizer_43;
  }
  get _Sanitizer_44():any {
    if ((this.__Sanitizer_44 == (null as any))) { (this.__Sanitizer_44 = this._DomSanitizer_43); }
    return this.__Sanitizer_44;
  }
  get _ViewUtils_45():import31.ViewUtils {
    if ((this.__ViewUtils_45 == (null as any))) { (this.__ViewUtils_45 = new import31.ViewUtils(this._RootRenderer_42,this._APP_ID_33,this._Sanitizer_44)); }
    return this.__ViewUtils_45;
  }
  get _IterableDiffers_46():any {
    if ((this.__IterableDiffers_46 == (null as any))) { (this.__IterableDiffers_46 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_46;
  }
  get _KeyValueDiffers_47():any {
    if ((this.__KeyValueDiffers_47 == (null as any))) { (this.__KeyValueDiffers_47 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_47;
  }
  get _ORIGIN_URL_48():any {
    if ((this.__ORIGIN_URL_48 == (null as any))) { (this.__ORIGIN_URL_48 = import4._ORIGIN_URL(this.parent.get(import54.NgZone))); }
    return this.__ORIGIN_URL_48;
  }
  get _REQUEST_URL_49():any {
    if ((this.__REQUEST_URL_49 == (null as any))) { (this.__REQUEST_URL_49 = import4._REQUEST_URL(this.parent.get(import54.NgZone))); }
    return this.__REQUEST_URL_49;
  }
  get _APP_BASE_HREF_50():any {
    if ((this.__APP_BASE_HREF_50 == (null as any))) { (this.__APP_BASE_HREF_50 = import4._APP_BASE_HREF(this.parent.get(import54.NgZone))); }
    return this.__APP_BASE_HREF_50;
  }
  get _PlatformLocation_51():import32.NodePlatformLocation {
    if ((this.__PlatformLocation_51 == (null as any))) { (this.__PlatformLocation_51 = new import32.NodePlatformLocation(this._ORIGIN_URL_48,this._REQUEST_URL_49,this._APP_BASE_HREF_50)); }
    return this.__PlatformLocation_51;
  }
  get _DomEventsPlugin_52():any[] {
    if ((this.__DomEventsPlugin_52 == (null as any))) { (this.__DomEventsPlugin_52 = [this._NodeDomEventsPlugin_35]); }
    return this.__DomEventsPlugin_52;
  }
  get _NodeEventManager_53():import4.NodeEventManager {
    if ((this.__NodeEventManager_53 == (null as any))) { (this.__NodeEventManager_53 = new import4.NodeEventManager(this._EVENT_MANAGER_PLUGINS_37,this._DOCUMENT_34,this.parent.get(import54.NgZone))); }
    return this.__NodeEventManager_53;
  }
  get _NodeSharedStylesHost_54():import33.NodeSharedStylesHost {
    if ((this.__NodeSharedStylesHost_54 == (null as any))) { (this.__NodeSharedStylesHost_54 = new import33.NodeSharedStylesHost()); }
    return this.__NodeSharedStylesHost_54;
  }
  get _NodeDomRootRenderer_55():import34.NodeDomRootRenderer {
    if ((this.__NodeDomRootRenderer_55 == (null as any))) { (this.__NodeDomRootRenderer_55 = new import34.NodeDomRootRenderer(this._DOCUMENT_34,this._EventManager_38,this._NodeSharedStylesHost_54,this._AnimationDriver_40)); }
    return this.__NodeDomRootRenderer_55;
  }
  get _SharedStylesHost_56():any {
    if ((this.__SharedStylesHost_56 == (null as any))) { (this.__SharedStylesHost_56 = this._DomSharedStylesHost_39); }
    return this.__SharedStylesHost_56;
  }
  get _XSRFStrategy_57():any {
    if ((this.__XSRFStrategy_57 == (null as any))) { (this.__XSRFStrategy_57 = import5._noop); }
    return this.__XSRFStrategy_57;
  }
  get _BrowserXhr_58():any {
    if ((this.__BrowserXhr_58 == (null as any))) { (this.__BrowserXhr_58 = import5._noop); }
    return this.__BrowserXhr_58;
  }
  get _RequestOptions_59():import35.BaseRequestOptions {
    if ((this.__RequestOptions_59 == (null as any))) { (this.__RequestOptions_59 = new import35.BaseRequestOptions()); }
    return this.__RequestOptions_59;
  }
  get _ResponseOptions_60():import36.BaseResponseOptions {
    if ((this.__ResponseOptions_60 == (null as any))) { (this.__ResponseOptions_60 = new import36.BaseResponseOptions()); }
    return this.__ResponseOptions_60;
  }
  get _XHRBackend_61():import5.NodeBackend {
    if ((this.__XHRBackend_61 == (null as any))) { (this.__XHRBackend_61 = new import5.NodeBackend(this._ResponseOptions_60,this._BrowserXhr_58,this._XSRFStrategy_57,this.parent.get(import54.NgZone),this._APP_BASE_HREF_50,this._ORIGIN_URL_48)); }
    return this.__XHRBackend_61;
  }
  get _Http_62():any {
    if ((this.__Http_62 == (null as any))) { (this.__Http_62 = import5.httpFactory(this._XHRBackend_61,this._RequestOptions_59)); }
    return this.__Http_62;
  }
  get _JSONPBackend_63():import5.NodeJsonpBackend_ {
    if ((this.__JSONPBackend_63 == (null as any))) { (this.__JSONPBackend_63 = new import5.NodeJsonpBackend_(this._ResponseOptions_60,this.parent.get(import54.NgZone),this._APP_BASE_HREF_50,this._ORIGIN_URL_48)); }
    return this.__JSONPBackend_63;
  }
  get _Jsonp_64():any {
    if ((this.__Jsonp_64 == (null as any))) { (this.__Jsonp_64 = import5.jsonpFactory(this._JSONPBackend_63,this._RequestOptions_59)); }
    return this.__Jsonp_64;
  }
  get _RadioControlRegistry_65():import37.RadioControlRegistry {
    if ((this.__RadioControlRegistry_65 == (null as any))) { (this.__RadioControlRegistry_65 = new import37.RadioControlRegistry()); }
    return this.__RadioControlRegistry_65;
  }
  get _FormBuilder_66():import38.FormBuilder {
    if ((this.__FormBuilder_66 == (null as any))) { (this.__FormBuilder_66 = new import38.FormBuilder()); }
    return this.__FormBuilder_66;
  }
  get _ROUTES_67():any[] {
    if ((this.__ROUTES_67 == (null as any))) { (this.__ROUTES_67 = [
      [
        {
          path: 'blog',
          component: import56.HomeComponent
        }
        ,
        {
          path: 'blog/:idCategory/:category',
          component: import56.HomeComponent
        }
        ,
        {
          path: 'blog/:idCategory/:idPost/:post',
          component: import56.HomeComponent
        }

      ]
      ,
        [{
          path: 'about',
          component: import57.AboutComponent
        }
      ],
        [{
          path: '',
          redirectTo: '/blog',
          pathMatch: 'full'
        }
      ],
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_67;
  }
  get _Title_68():import39.Title {
    if ((this.__Title_68 == (null as any))) { (this.__Title_68 = new import39.Title()); }
    return this.__Title_68;
  }
  get _ROUTER_CONFIGURATION_69():any {
    if ((this.__ROUTER_CONFIGURATION_69 == (null as any))) { (this.__ROUTER_CONFIGURATION_69 = {useHash: false}); }
    return this.__ROUTER_CONFIGURATION_69;
  }
  get _LocationStrategy_70():any {
    if ((this.__LocationStrategy_70 == (null as any))) { (this.__LocationStrategy_70 = import9.provideLocationStrategy(this._PlatformLocation_51,this._APP_BASE_HREF_50,this._ROUTER_CONFIGURATION_69)); }
    return this.__LocationStrategy_70;
  }
  get _Location_71():import40.Location {
    if ((this.__Location_71 == (null as any))) { (this.__Location_71 = new import40.Location(this._LocationStrategy_70)); }
    return this.__Location_71;
  }
  get _UrlSerializer_72():import41.DefaultUrlSerializer {
    if ((this.__UrlSerializer_72 == (null as any))) { (this.__UrlSerializer_72 = new import41.DefaultUrlSerializer()); }
    return this.__UrlSerializer_72;
  }
  get _RouterOutletMap_73():import42.RouterOutletMap {
    if ((this.__RouterOutletMap_73 == (null as any))) { (this.__RouterOutletMap_73 = new import42.RouterOutletMap()); }
    return this.__RouterOutletMap_73;
  }
  get _NgModuleFactoryLoader_74():import43.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_74 == (null as any))) { (this.__NgModuleFactoryLoader_74 = new import43.SystemJsNgModuleLoader(this._Compiler_32,this.parent.get(import43.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_74;
  }
  get _Router_75():any {
    if ((this.__Router_75 == (null as any))) { (this.__Router_75 = import9.setupRouter(this._ApplicationRef_31,this._UrlSerializer_72,this._RouterOutletMap_73,this._Location_71,this,this._NgModuleFactoryLoader_74,this._Compiler_32,this._ROUTES_67,this._ROUTER_CONFIGURATION_69)); }
    return this.__Router_75;
  }
  get _ActivatedRoute_76():any {
    if ((this.__ActivatedRoute_76 == (null as any))) { (this.__ActivatedRoute_76 = import9.rootRoute(this._Router_75)); }
    return this.__ActivatedRoute_76;
  }
  get _PreloadAllModules_80():import44.PreloadAllModules {
    if ((this.__PreloadAllModules_80 == (null as any))) { (this.__PreloadAllModules_80 = new import44.PreloadAllModules()); }
    return this.__PreloadAllModules_80;
  }
  get _APP_BOOTSTRAP_LISTENER_81():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_81 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_81 = [import9.initialRouterNavigation(this._Router_75,this._ApplicationRef_31,this._RouterPreloader_79,this._ROUTER_CONFIGURATION_69)]); }
    return this.__APP_BOOTSTRAP_LISTENER_81;
  }
  get _ApiService_82():import45.ApiService {
    if ((this.__ApiService_82 == (null as any))) { (this.__ApiService_82 = new import45.ApiService(this._Http_62)); }
    return this.__ApiService_82;
  }
  get _ModelService_83():import46.ModelService {
    if ((this.__ModelService_83 == (null as any))) { (this.__ModelService_83 = new import46.ModelService(this._ApiService_82,this._CacheService_22)); }
    return this.__ModelService_83;
  }
  get _isBrowser_84():any {
    if ((this.__isBrowser_84 == (null as any))) { (this.__isBrowser_84 = import58.isBrowser); }
    return this.__isBrowser_84;
  }
  get _isNode_85():any {
    if ((this.__isNode_85 == (null as any))) { (this.__isNode_85 = true); }
    return this.__isNode_85;
  }
  get _req_86():any {
    if ((this.__req_86 == (null as any))) { (this.__req_86 = import1.getRequest()); }
    return this.__req_86;
  }
  get _res_87():any {
    if ((this.__res_87 == (null as any))) { (this.__res_87 = import1.getResponse()); }
    return this.__res_87;
  }
  get _Meta_88():import47.Meta {
    if ((this.__Meta_88 == (null as any))) { (this.__Meta_88 = new import47.Meta()); }
    return this.__Meta_88;
  }
  createInternal():import1.MainModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._NodeModule_2 = new import4.NodeModule(this.parent.get(import4.NodeModule,(null as any)));
    this._NodeHttpModule_3 = new import5.NodeHttpModule();
    this._NodeJsonpModule_4 = new import5.NodeJsonpModule();
    this._UniversalModule_5 = new import6.UniversalModule();
    this._InternalFormsSharedModule_6 = new import7.InternalFormsSharedModule();
    this._FormsModule_7 = new import8.FormsModule();
    this._ROUTER_FORROOT_GUARD_8 = import9.provideForRootGuard(this.parent.get(import59.Router,(null as any)));
    this._RouterModule_9 = new import9.RouterModule(this._ROUTER_FORROOT_GUARD_8);
    this._ReactiveFormsModule_10 = new import8.ReactiveFormsModule();
    this._SharedModule_11 = new import10.SharedModule();
    this._HomeRoutingModule_12 = new import11.HomeRoutingModule();
    this._PostModule_13 = new import12.PostModule();
    this._PostDetailModule_14 = new import13.PostDetailModule();
    this._BrowserModule_15 = new import14.BrowserModule(this.parent.get(import14.BrowserModule,(null as any)));
    this._HomeModule_16 = new import15.HomeModule();
    this._AboutRoutingModule_17 = new import16.AboutRoutingModule();
    this._AboutModule_18 = new import17.AboutModule();
    this._AppRoutingModule_19 = new import18.AppRoutingModule();
    this._AppModule_20 = new import19.AppModule();
    this._LRU_21 = import1.getLRU();
    this._CacheService_22 = new import20.CacheService(this._LRU_21);
    this._MainModule_23 = new import1.MainModule(this._CacheService_22);
    this._ErrorHandler_26 = import14.errorHandler();
    this._ApplicationInitStatus_27 = new import22.ApplicationInitStatus(this.parent.get(import22.APP_INITIALIZER,(null as any)));
    this._TestabilityRegistry_28 = new import4.MockTestabilityRegistry();
    this._Testability_29 = new import23.Testability(this.parent.get(import54.NgZone));
    this._ApplicationRef__30 = new import24.ApplicationRef_(this.parent.get(import54.NgZone),this.parent.get(import60.Console),this,this._ErrorHandler_26,this,this._ApplicationInitStatus_27,this._TestabilityRegistry_28,this._Testability_29);
    this._NoPreloading_77 = new import44.NoPreloading();
    this._PreloadingStrategy_78 = this._NoPreloading_77;
    this._RouterPreloader_79 = new import44.RouterPreloader(this._Router_75,this._NgModuleFactoryLoader_74,this._Compiler_32,this,this._PreloadingStrategy_78);
    return this._MainModule_23;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.NodeModule)) { return this._NodeModule_2; }
    if ((token === import5.NodeHttpModule)) { return this._NodeHttpModule_3; }
    if ((token === import5.NodeJsonpModule)) { return this._NodeJsonpModule_4; }
    if ((token === import6.UniversalModule)) { return this._UniversalModule_5; }
    if ((token === import7.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_6; }
    if ((token === import8.FormsModule)) { return this._FormsModule_7; }
    if ((token === import9.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_8; }
    if ((token === import9.RouterModule)) { return this._RouterModule_9; }
    if ((token === import8.ReactiveFormsModule)) { return this._ReactiveFormsModule_10; }
    if ((token === import10.SharedModule)) { return this._SharedModule_11; }
    if ((token === import11.HomeRoutingModule)) { return this._HomeRoutingModule_12; }
    if ((token === import12.PostModule)) { return this._PostModule_13; }
    if ((token === import13.PostDetailModule)) { return this._PostDetailModule_14; }
    if ((token === import14.BrowserModule)) { return this._BrowserModule_15; }
    if ((token === import15.HomeModule)) { return this._HomeModule_16; }
    if ((token === import16.AboutRoutingModule)) { return this._AboutRoutingModule_17; }
    if ((token === import17.AboutModule)) { return this._AboutModule_18; }
    if ((token === import18.AppRoutingModule)) { return this._AppRoutingModule_19; }
    if ((token === import19.AppModule)) { return this._AppModule_20; }
    if ((token === 'LRU')) { return this._LRU_21; }
    if ((token === import20.CacheService)) { return this._CacheService_22; }
    if ((token === import1.MainModule)) { return this._MainModule_23; }
    if ((token === import61.LOCALE_ID)) { return this._LOCALE_ID_24; }
    if ((token === import21.NgLocalization)) { return this._NgLocalization_25; }
    if ((token === import62.ErrorHandler)) { return this._ErrorHandler_26; }
    if ((token === import22.ApplicationInitStatus)) { return this._ApplicationInitStatus_27; }
    if ((token === import23.TestabilityRegistry)) { return this._TestabilityRegistry_28; }
    if ((token === import23.Testability)) { return this._Testability_29; }
    if ((token === import24.ApplicationRef_)) { return this._ApplicationRef__30; }
    if ((token === import24.ApplicationRef)) { return this._ApplicationRef_31; }
    if ((token === import25.Compiler)) { return this._Compiler_32; }
    if ((token === import63.APP_ID)) { return this._APP_ID_33; }
    if ((token === import64.DOCUMENT)) { return this._DOCUMENT_34; }
    if ((token === import4.NodeDomEventsPlugin)) { return this._NodeDomEventsPlugin_35; }
    if ((token === import26.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_36; }
    if ((token === import27.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_37; }
    if ((token === import27.EventManager)) { return this._EventManager_38; }
    if ((token === import28.DomSharedStylesHost)) { return this._DomSharedStylesHost_39; }
    if ((token === import65.AnimationDriver)) { return this._AnimationDriver_40; }
    if ((token === import29.DomRootRenderer)) { return this._DomRootRenderer_41; }
    if ((token === import66.RootRenderer)) { return this._RootRenderer_42; }
    if ((token === import30.DomSanitizer)) { return this._DomSanitizer_43; }
    if ((token === import67.Sanitizer)) { return this._Sanitizer_44; }
    if ((token === import31.ViewUtils)) { return this._ViewUtils_45; }
    if ((token === import68.IterableDiffers)) { return this._IterableDiffers_46; }
    if ((token === import69.KeyValueDiffers)) { return this._KeyValueDiffers_47; }
    if ((token === import70.ORIGIN_URL)) { return this._ORIGIN_URL_48; }
    if ((token === import70.REQUEST_URL)) { return this._REQUEST_URL_49; }
    if ((token === import71.APP_BASE_HREF)) { return this._APP_BASE_HREF_50; }
    if ((token === import72.PlatformLocation)) { return this._PlatformLocation_51; }
    if ((token === import53.DomEventsPlugin)) { return this._DomEventsPlugin_52; }
    if ((token === import4.NodeEventManager)) { return this._NodeEventManager_53; }
    if ((token === import33.NodeSharedStylesHost)) { return this._NodeSharedStylesHost_54; }
    if ((token === import34.NodeDomRootRenderer)) { return this._NodeDomRootRenderer_55; }
    if ((token === import28.SharedStylesHost)) { return this._SharedStylesHost_56; }
    if ((token === import73.XSRFStrategy)) { return this._XSRFStrategy_57; }
    if ((token === import74.BrowserXhr)) { return this._BrowserXhr_58; }
    if ((token === import35.RequestOptions)) { return this._RequestOptions_59; }
    if ((token === import36.ResponseOptions)) { return this._ResponseOptions_60; }
    if ((token === import75.XHRBackend)) { return this._XHRBackend_61; }
    if ((token === import76.Http)) { return this._Http_62; }
    if ((token === import77.JSONPBackend)) { return this._JSONPBackend_63; }
    if ((token === import76.Jsonp)) { return this._Jsonp_64; }
    if ((token === import37.RadioControlRegistry)) { return this._RadioControlRegistry_65; }
    if ((token === import38.FormBuilder)) { return this._FormBuilder_66; }
    if ((token === import78.ROUTES)) { return this._ROUTES_67; }
    if ((token === import39.Title)) { return this._Title_68; }
    if ((token === import9.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_69; }
    if ((token === import71.LocationStrategy)) { return this._LocationStrategy_70; }
    if ((token === import40.Location)) { return this._Location_71; }
    if ((token === import41.UrlSerializer)) { return this._UrlSerializer_72; }
    if ((token === import42.RouterOutletMap)) { return this._RouterOutletMap_73; }
    if ((token === import79.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_74; }
    if ((token === import59.Router)) { return this._Router_75; }
    if ((token === import80.ActivatedRoute)) { return this._ActivatedRoute_76; }
    if ((token === import44.NoPreloading)) { return this._NoPreloading_77; }
    if ((token === import44.PreloadingStrategy)) { return this._PreloadingStrategy_78; }
    if ((token === import44.RouterPreloader)) { return this._RouterPreloader_79; }
    if ((token === import44.PreloadAllModules)) { return this._PreloadAllModules_80; }
    if ((token === import63.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_81; }
    if ((token === import45.ApiService)) { return this._ApiService_82; }
    if ((token === import46.ModelService)) { return this._ModelService_83; }
    if ((token === 'isBrowser')) { return this._isBrowser_84; }
    if ((token === 'isNode')) { return this._isNode_85; }
    if ((token === 'req')) { return this._req_86; }
    if ((token === 'res')) { return this._res_87; }
    if ((token === import47.Meta)) { return this._Meta_88; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__30.ngOnDestroy();
    this._RouterPreloader_79.ngOnDestroy();
  }
}
export const MainModuleNgFactory:import0.NgModuleFactory<import1.MainModule> = new import0.NgModuleFactory(MainModuleInjector,import1.MainModule);