/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './postDetail.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/forms/src/directives';
import * as import5 from '@angular/forms/src/form_providers';
import * as import6 from '../shared/shared.module';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '@angular/core/src/di/injector';
import * as import11 from '@angular/core/src/i18n/tokens';
class PostDetailModuleInjector extends import0.NgModuleInjector<import1.PostDetailModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _InternalFormsSharedModule_2:import4.InternalFormsSharedModule;
  _FormsModule_3:import5.FormsModule;
  _ReactiveFormsModule_4:import5.ReactiveFormsModule;
  _SharedModule_5:import6.SharedModule;
  _PostDetailModule_6:import1.PostDetailModule;
  __NgLocalization_7:import7.NgLocaleLocalization;
  __RadioControlRegistry_8:import8.RadioControlRegistry;
  __FormBuilder_9:import9.FormBuilder;
  constructor(parent:import10.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_7():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == (null as any))) { (this.__NgLocalization_7 = new import7.NgLocaleLocalization(this.parent.get(import11.LOCALE_ID))); }
    return this.__NgLocalization_7;
  }
  get _RadioControlRegistry_8():import8.RadioControlRegistry {
    if ((this.__RadioControlRegistry_8 == (null as any))) { (this.__RadioControlRegistry_8 = new import8.RadioControlRegistry()); }
    return this.__RadioControlRegistry_8;
  }
  get _FormBuilder_9():import9.FormBuilder {
    if ((this.__FormBuilder_9 == (null as any))) { (this.__FormBuilder_9 = new import9.FormBuilder()); }
    return this.__FormBuilder_9;
  }
  createInternal():import1.PostDetailModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._InternalFormsSharedModule_2 = new import4.InternalFormsSharedModule();
    this._FormsModule_3 = new import5.FormsModule();
    this._ReactiveFormsModule_4 = new import5.ReactiveFormsModule();
    this._SharedModule_5 = new import6.SharedModule();
    this._PostDetailModule_6 = new import1.PostDetailModule();
    return this._PostDetailModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_2; }
    if ((token === import5.FormsModule)) { return this._FormsModule_3; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.SharedModule)) { return this._SharedModule_5; }
    if ((token === import1.PostDetailModule)) { return this._PostDetailModule_6; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import8.RadioControlRegistry)) { return this._RadioControlRegistry_8; }
    if ((token === import9.FormBuilder)) { return this._FormBuilder_9; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const PostDetailModuleNgFactory:import0.NgModuleFactory<import1.PostDetailModule> = new import0.NgModuleFactory(PostDetailModuleInjector,import1.PostDetailModule);